### ISSUE TITLE
No keywords in case of using relative path for lib

### ISSUE THREAD

**Issue by yoursen** [nokia/RED#10]
Hi team! thank you very much for this IDE, it's really great and I'm looking forward for new updates. Despite I have one issue that I cannot figure out how to resolve it.
I have a project in eclipse which contains separate folders for tests and python libs. I added these libs into RED xml with relative path, but after that eclipse doesn't  see the keywords.
If I use absolute paths in red.xml everything works fine.
![screenshot](https://cloud.githubusercontent.com/assets/18039730/14002679/240978f8-f156-11e5-8862-b755df75f0ff.png)

Could you help me with this issue?

**Comment by KrzysztofJozefowicz** [comment]
Hi
Thanks for kind words, we are glad that you like it. 
We would like to reproduce your case as using plain python such lib referencing works correctly, this may be something with ironpython env. Best way would be to share that project (or at least sample libs and dependencies) but if you cannot (due to legal reasons) let's try to find root cause here.

Before we start, can you show Problems view so we could see the errors associated with line 2 and 3? Go to Window-> Show View -> Problems

1. First have a look into Robot Referenced libraries in Project Explorer. MenuApplet and Log4netUtils shows that Keywords were generated ( in fact one KW per lib ), can you verify if this is valid (list of KW from Robot Referenced libraries are the same as from lib files)? 
2. If not, try to generate list of KW manually to check if Robot itself can do it (RED calls Robot to return keyword list) using [link to robot libdoc](http://robot-framework.readthedocs.org/en/2.9.1/_modules/robot/libdoc.html) : 
`ipy -m robot.libdoc [options] <PATH TO MenuApplet.py>`
Output should produce same list of KW as in RED and in libs. If any error is returned, this indicates problems with ironpython paths 
3. Does those libs have any dependencies to dotNet resources?
4. For testing purposes you can do following:
 - add those libs to red.xml if not yet added
 - change Settings part to following:

`Library  MenuApplet`
`Library  Log4netUtils `


- execute Project -> Clean to revalidate whole Project
- check if errors markers are still present

**Comment by yoursen** [comment]
Thank you for suggestions. Seems I found the issue during preparation of sample project for you.
So I have created Sample project and everything works for me, It was weird, so I compared it to my original project and difference is that original project is located outside of default eclipse workspace, it was just imported.
And if moved out my new sample project out of workspace, then import it I got the issue.

**Comment by KrzysztofJozefowicz** [comment]
Thanks for reply, we will check it on our side and provide fix for relative paths for files/folders outside of workspace/project.
In essence, bast way is to checkout files directly to Project folder or at least import with copying files.
