### ISSUE TITLE
Headings don't get displayed in TestCases tab

### ISSUE THREAD

**Issue by BeastModeActivated** [nokia/RED#100]
Heading mentioned in test cases are not displayed in RED.
I have attached reference of RIDE as well where they are displayed. (Action, Field1, Field2)

![0 source](https://cloud.githubusercontent.com/assets/10611789/24703126/823b43a0-1a1f-11e7-9dcd-68e9ab8979bf.jpg)
![1 ride](https://cloud.githubusercontent.com/assets/10611789/24703130/886413ce-1a1f-11e7-9094-05bf740a1ae2.jpg)
![2 red](https://cloud.githubusercontent.com/assets/10611789/24703131/88644c5e-1a1f-11e7-8e98-9bf4e40729f1.jpg)

**Comment by KrzysztofJozefowicz** [comment]
Hi
This is RIDE way of displaying table headers. In our opinion it is not wise to use undocumented/unhandled cases in Robot for column naming - nobody can guarantee that in next versions Robot will omit additional entries in the same line as section name ( *** Testcases ***). 
From user perspective, such column naming is not flexible enough - testcases needs to resemble what is written in column header and is only visible in RIDE.
From above we will not provide RIDE way in RED.

Better option,which is in fact used by many teams in Nokia, is to create a commented line with separators between column naming:
```
t1
  #keyword  arg1  arg2  arg3
  log many  one  two  three
```
This way you can provide comments per TC,KW or user keyword one by one if needed. With source reformat (ctrl+shift+f), source code will be evenly spaced.

**Comment by adam-wypych** [comment]
Hi,

To be honest the syntax presented by @BeastModeActivated is described in RF documentation see: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id487 (_When using normal arguments, the same effect can be achieved by naming the columns that contain arguments._) and http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id491 (_Naming columns like in the example above makes tests easier to understand. This is possible because on the header row other cells except the first one are ignored._).

As I see https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/testdata/model/table/TableHeader.java still is possible to get column names by using 

> `List<RobotToken> getColumnNames()`

**Comment by BeastModeActivated** [comment]
As per the comment above and going through the documentation, it implies that robot framework does support naming of user defined headers.
I think RED should also follow the way it is documented.
What do you think @KrzysztofJozefowicz ?

**Comment by michalanglart** [comment]
Provided in 0.9.3
