### ISSUE TITLE
TestRunnerAgent crashes with error "No enum constant org.rf.ide.core.execution.LogLevel.ERROR" When SOAP call returns error

### ISSUE THREAD

**Issue by pingmaster** [nokia/RED#102]
![image](https://cloud.githubusercontent.com/assets/27239913/24880782/a357d7ae-1e09-11e7-9a1f-9e1696f724ba.png)

When running a test that calls a SOAP method (via SudsLibrary), if the API returns an error, the test runner crashes with the above message. Looking through the source, it's apparent that the enum org.rf.ide.core.execution.LogLevel does not include ERROR. This is a new issue since updating to the latest release 0.7.6. SudsLibrary has not changed and Robot is up to date.

**Comment by michalanglart** [comment]
Hi,

indeed this a bug introduced in 0.7.6. Up to 0.7.5 the log level sent from execution was passed as string in RED. From 0.7.6 it was changed to use enum constant, however the avaiable log levels were taken from RF documentation instead of Robot code: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#log-levels Appareantly documentation is wrong here.

We'll fix that. As for now only reverting to 0.7.5 is an option to prevent this.

**Comment by KrzysztofJozefowicz** [comment]
closed and released in 0.7.7
