### ISSUE TITLE
Dynamic variable generation - Ignore error for undefined variables

### ISSUE THREAD

**Issue by FSaccilotto** [nokia/RED#104]
Hi everyone,
we are searching for a better Robot IDE than RIDE and found your eclipse based IDE.
A lot of think work really nice, thank you very much for providing this!

In a current project we have implemented a feature to create variables dynamically from an excel sheet. With the current settings all those variables are marked as errors which pollutes the error log from real errors. Is there a way change this validation into a warning or deactivate validation for parts of a certain file?

Regards Fabian

**Comment by michalanglart** [comment]
Hi,

great to hear RED is working for you!

In general you can change severity of reported problems (or category of problems to be more precise) in Preferences: Window -> Preferences -> Robot Framework -> Errors/Warnings. However as for now the error we are talking about is currently assigned to category 'Runtime' / 'Robot Framework runtime error' in which severity cannot be changed. We'll discuss this matter and let you know how we want to address this issue (i.e. by enabling this preference, or assigning the problem to different category).

There is also possibility to omit some parts of your project during validation, but it works by ignoring whole directories with subdirectories and files, so I guess this not something you want to use. Anyway it can be configured in red.xml file. Open the file in editor and at 'Validation' page you may exclude certain parts of your project (right mouse button on directory/file).

We currently do not have the possibility to somehow suppress validation error just in single line. We had couple of ideas how it may work, we also have open issue for this in our internal issues tracker, but as for now there is no implementation.

Last but not least you can use kind of a workaround: in red.xml file you may specify variables file. The file is simply variables file as described in http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-files and RED is always taking this file to execution when launching tests by using --variablefile switch. However because of that RED sees variables defined in those files in every suite/resource file defined in project. This may work as a workaround - you simple define variable names which you want to have recognized inside a variables file; attach it in red.xml. As a result validation from now will see this variable in every single file thus the error will not be produced.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Can you provide an example how do you use dynamic variables generated from excel,this would help us in discussion how we could implement changing errors/warnings . 
How "dynamic" are those vars - amount and var names differs, are they used in exact places in robot testcases etc.

**Comment by FSaccilotto** [comment]
Hi,

 

thank you for your fast response!

 

I indeed already looked into the notifications settings and the validation excludes.

 

Your hint with the dummy variables works for me. The errors are gone and the tests still run correctly.

Thanks a lot.

 

Regards Fabian

 

 

Gesendet: Mittwoch, 26. April 2017 um 09:20 Uhr
Von: michalanglart <notifications@github.com>
An: nokia/RED <RED@noreply.github.com>
Cc: "Fabian Saccilotto" <f.saccilotto@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [nokia/RED] Dynamic variable generation - Ignore error for undefined variables (#104)


Hi,

great to hear RED is working for you!

In general you can change severity of reported problems (or category of problems to be more precise) in Preferences: Window -> Preferences -> Robot Framework -> Errors/Warnings. However as for now the error we are talking about is currently assigned to category 'Runtime' / 'Robot Framework runtime error' in which severity cannot be changed. We'll discuss this matter and let you know how we want to address this issue (i.e. by enabling this preference, or assigning the problem to different category).

There is also possibility to omit some parts of your project during validation, but it works by ignoring whole directories with subdirectories and files, so I guess this not something you want to use. Anyway it can be configured in red.xml file. Open the file in editor and at 'Validation' page you may exclude certain parts of your project (right mouse button on directory/file).

We currently do not have the possibility to somehow suppress validation error just in single line. We had couple of ideas how it may work, we also have open issue for this in our internal issues tracker, but as for now there is no implementation.

Last but not least you can use kind of a workaround: in red.xml file you may specify variables file. The file is simply variables file as described in http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-files and RED is always taking this file to execution when launching tests by using --variablefile switch. However because of that RED sees variables defined in those files in every suite/resource file defined in project. This may work as a workaround - you simple define variable names which you want to have recognized inside a variables file; attach it in red.xml. As a result validation from now will see this variable in every single file thus the error will not be produced.
