### ISSUE TITLE
Update to RED 0.7.7 from 0.7.2 run Configuration not Properly passing Additional Robot Framework arguments

### ISSUE THREAD

**Issue by mrosenhahn** [nokia/RED#106]
The change to the run configuration between release 0.7.2 to 0.7.7 broke the way that  the run configuration handles the Additional Robot Framework arguments.

In 0.7.2 My run configuration was setup as follows:
![0_7_2](https://cloud.githubusercontent.com/assets/25513789/25673297/a9d20bba-2feb-11e7-8d8b-f79ee23f9a1b.JPG)

After upgrade the parameters had been moved around so when I placed the values in the same fields the same fields, the Additional Robot Framework arguments is not being properly passed along with the Additional interpreter arguments. I know this because the *ini file I am passing in is not being looked at by my script

![0_7_7page_1](https://cloud.githubusercontent.com/assets/25513789/25673404/29829fe6-2fec-11e7-8b1f-6447facee271.JPG)

![0_7_7page_2](https://cloud.githubusercontent.com/assets/25513789/25673434/3e6c1a90-2fec-11e7-988d-eaa6e4fdfdba.JPG)

Editing:
**When run from RED 0.7.2 the command specified is** 

>  Command: /opt/ActivePython-2.7/bin/python /etc/barista/repos/cafe/calix/src/caferobot/cafebot.py -m robot.run -P /etc/barista/packages/caferobot:/etc/barista/packages/caferobot/command:/etc/barista/packages/caferobot/web:/etc/barista/packages/caferobot/trafficgen:/etc/barista/packages/caferobot/resp:/etc/barista/packages/caferobot/result:/etc/barista/packages/caferobot/util:/etc/barista/packages/caferobot/restful:/etc/barista/packages/caferobot/var:/etc/barista/packages/caferobot/netconf:/etc/barista/packages/caferobot/snmp:/etc/barista/packages/caferobot/listener:/etc/barista/packages/caferobot/temp_res:/etc/barista/packages/caferobot/fiber_cut_box:/etc/barista/packages/caferobot/debug:/home/mrosenha/git/xdsl-automation/Prem_bw_test/bw_test_gpon/lib:/opt/ActivePython-2.7/lib/python2.7/site-packages/robot/libraries --listener /tmp/RobotTempDir5366750581460820609/TestRunnerAgent.py:53677:False -s Prem_bw_test.Bw_test_gpon.Gpon_Bw_testing_RG_ONT_single_tagged.Test Bandwidth.Test Upstream Bandwidth -s **Prem_bw_test.Bw_test_gpon.Gpon_Bw_testing_RG_ONT_single_tagged.Test Bandwidth.Test Downstream Bandwidth --config_file /home/mrosenha/git/xdsl-automation/Prem_bw_test/bw_test_gpon/config/bandwidth_profile_5M_config.ini** /home/mrosenha/git/xdsl-automation/Prem_bw_test
> Suite Executor: Robot Framework 3.0.2 (Python 2.7.8 on linux2)

**When Run from RED 0.7.7** The specified ini file not present in the command string

> Command: /opt/ActivePython-2.7/bin/python /etc/barista/repos/cafe/calix/src/caferobot/cafebot.py -m robot.run --listener /tmp/RobotTempDir8618016074133046876/TestRunnerAgent.py:58157 --argumentfile /tmp/RobotTempDir8618016074133046876/args_e22224ea.arg /home/mrosenha/git/xdsl-automation/Prem_bw_test
> Suite Executor: Robot Framework 3.0.2 (Python 2.7.8 on linux2)

I have tried moving the values to the Executable file section but this ends up failing for an Unsupported file format.

How am I to translate my old run configurations to the new run configuration format so that my tests can run?

**Comment by michalanglart** [comment]
Hi,

From RED 0.7.6 almost all the arguments for Robot are passed using argument file (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#argument-files) by default. If you take a look into your /tmp/RobotTempDir8618016074133046876/args_e22224ea.arg file (it's temporary so now it probably does not exist) you will find that there is a line containing your config_file switch. 

You may disable this behavior in Preferences: Window -> Preferences -> Robot Framework -> Launching and uncheck box 'Pass Robot arguments using arguments file'.

This should somehow fix your problem, however I strongly recommend looking into RED's help topic about launching tests: http://nokia.github.io/RED/help/user_guide/launching.html + subtopics, or simply Open Help -> Help Contents in your running RED instance). It looks like you've developed a workaround in order to run tests through custom script. With RED 0.7.2 you have injected different script for execution using 'additional interpreter arguments' field and then your script launches Robot (am I right?). One sign of something being worked around is that the config_file argument is passed via 'additional Robot arguments' but in fact this is not an argument for Robot. 

The good news is that the possibility to execute tests via custom scripts is directly addressed from RED 0.7.6 - you may execute tests using any script you like. Please refer to user guide and feel free to ask here if something is not clear enough.

Last but not least: from RED 0.7.5 you may specify default values for some fields in launch configuration, so when new launch configuration is created it will use those values as a template. This can be done also in Preferences: Robot Framework -> Launching -> Default Launch Configuration.

**Comment by mrosenhahn** [comment]
Thank you for the feedback.

The fix for me to get things running again was to **Preferences: Window -> Preferences -> Robot Framework -> Launching and uncheck box 'Pass Robot arguments using arguments file'.**
