### ISSUE TITLE
Detection Remote Library and Read Keyword Documentation from Remote Server in RED.

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#108]
Dear RED Team,
We have problem with detection Remote Library and Read Keyword Documentation from Remote Server in RED.
We have C# Remote Libraries with NRobotRemote (XML-RPC) Server. RIDE can read Keyword and Dokumentation from Remote Server about Remote Library.  RED can't detection Remote Library and Library from Remote Server.
Robot can run keyword from Remote XML-RPC with RIDE and RED.

I have one example to reproduce this problem.
[test-environment.zip](https://github.com/nokia/RED/files/1001356/test-environment.zip)

1. You must unzip example local.
2. You must start test-environment\libraries\net\StartLibraries.exe as Administrator.
3. Open Project with RED from test-environment.
4. You can see in suite-sum.robot the Keyword SUM can't detection from red.

![red remote issue](https://cloud.githubusercontent.com/assets/18263592/26062312/c2b31248-398a-11e7-9e80-278ecccbcccc.jpg)

Thank You very match

**Comment by michalanglart** [comment]
Hi,

thank you for providing problematic example - it took me just couple of minutes to see what is going on.

Your example will work, you just need to configure red.xml a little bit differently, because Remote libraries have special configuration:

- firstly please remove the 'Remote' library from red.xml 
- use 'Add Remote location' button and type address you want to use (http://127.0.0.1:8273/StartLibraries.TestLibrary in your case; marked red on image)
- after saving red.xml and building the project library specification should be properly generated, so you should see your library in project explorer and validation error should be gone
- validation is reporting problems in red.xml if it cannot connect to specified address, the image of a library is also showing this (it's either green or red; green on image below, since the server is running on my pc)

![remote_config](https://cloud.githubusercontent.com/assets/14932410/26075749/a9ca0724-39b6-11e7-9550-93f674bf9a5b.png)

I admit this a little bit non-intuitive probably, but we still lack generic support for parameterized libraries (see #47) and Remote library is the only one for which support was implemented, however maybe it requires some rethinking...

**Comment by michalanglart** [comment]
Here's a screenshot when configuration is done as described above:

![remote_working](https://cloud.githubusercontent.com/assets/14932410/26076222/475e9a12-39b8-11e7-8a52-bf9be6de110f.png)

**Comment by AndreasRusjaev** [comment]
Thank You very match.
Now works correctly.
Could you please supplement the user documentation. I have this not found in documentation.
Thanks again for help.

**Comment by KrzysztofJozefowicz** [comment]
Good catch, we will update docs to show how to use RemoteLib.

**Comment by AndreasRusjaev** [comment]
Thank You
