### ISSUE TITLE
Ignore variables mapping errors

### ISSUE THREAD

**Issue by lolotoms** [nokia/RED#123]
Hi,

I have to run my test in differents languages. To do this, I pass language argument to my test like --variable language:FR and I import my var file, according to language, when I run the test. 

Because of I never import var file from Setting, RED shows errors for all variables of my test, even if the execution is OK. 

Is there a way to ignore this errors? I tried preferences -> RF -> errors/warning conf but don't find nothing.

**Comment by michalanglart** [comment]
Hi,

this particular error (use of undeclared variable) is under 'Robot Framework runtime error' category in preferences, however as of now it cannot be changed. There is also no mechanism which would silence particular errors in particular files - we plan to implement such feature, but it is hard to say when it will be available.

There is a way in which you can silence those errors - by globally importing variable file. You can prepare .py file with those variables and import them in red.xml (open editor, 'Variable files' tab). You will not see those errors, because variables imported in this way are visible globally, however RED will always add --variablefile when running tests.

**Comment by lolotoms** [comment]
Hi, thanks for the answer. I will try this

**Comment by hpschry** [comment]
Hi, 
we have nearly the same issue as we calculate items dynamically to a python object, that we access by the extended robot framework syntax. We get an error for each of those, which is a major share of all messages.

**Comment by KrzysztofJozefowicz** [comment]
since 0.8.3 user can switch off validation from Preferences:
http://nokia.github.io/RED/help/user_guide/validation/validation_preferences.html
