### ISSUE TITLE
links to resources don't work if using global path variable 

### ISSUE THREAD

**Issue by Galgc** [nokia/RED#128]
in our code in order to support windows and linux path notation we call our resources using the built in path variable "${/}".
so when I have the following resource:
Resource  ..${/}..${/}path${/}resourceFile.robot
It will not be identified as a resource and I cannot follow links into that resource.
However if (on windows) I write:
..\..\path\resourceFile.robot , the resource will be identified and you can follow (follow links in the code) into calls from that file.

**Comment by michalanglart** [comment]
Hi,

Please take a look into this topic in RED help: http://nokia.github.io/RED/help/user_guide/working_with_RED/variable_mapping.html

RED only uses mappings defined in red.xml to resolve paths to library or resources imports. You can define ${/} to be replaced with proper value so that your code will not be affected. 

On the other hand from what I remember it works under both windows and linux when / is used as segments separator in resource or library imports.

**Comment by Galgc** [comment]
We currently don't have a red.xml file in our environment and adding this
will require me to add a new resource that is verify specific to
eclipse/red. AFAIK the editor that can be found on IDEA IDE does not
require this file to handle that mapping.

While I can add that it seems that the {/} variable is robot internal to
robot (see here -
http://robotframework.org/robotframework/latest/libraries/OperatingSystem.html
under Path Seperators) and I expected that robot internal variables will be
supported.

**Comment by michalanglart** [comment]
>  I expected that robot internal variables will be supported.

Today I was able to check it and your case works in newest version as well as 0.7.0 and later (I haven't checked earlier 0.6.x) so it seems that we handle ${/} variable in imports for more than a year. What RED version do you use?

With following simple project I'm able to click on resource import in suite.robot file and it properly opens the target file. Also validation does not report any error which means it properly recognizes this import.

[slash.zip](https://github.com/nokia/RED/files/1204079/slash.zip)

> We currently don't have a red.xml file in our environment and adding this will require me to add a new resource that is verify specific to eclipse/red. AFAIK the editor that can be found on IDEA IDE does not require this file to handle that mapping.

RED uses red.xml file as a configuration file for the project. For example it will generate library specifications only for libraries which are added to red.xml. This mean that RED will not see the keywords from 3rd party libraries unless those libraries are added to this configuration file. In nearest future it does not seem that RED will stop using red.xml file. 

You can also ignore this file for version control so that it will not be commited to your repository.

**Comment by Galgc** [comment]
that is strange. I'm using 0.7.9(201706290901)
I wll try to add the red.xml file and see if it helps

**Comment by michalanglart** [comment]
In fact nothing has to be added to red.xml. Please take a look at slash.zip project I have attached. There is nothing added to red.xml and single suite file imports another using ${/}.

**Comment by Galgc** [comment]
So my results in "debugging" this:
If I don't have the red.xml, the links do not work.
If I add the empty red.xml (from the slash.zip) links start to work.
if I delete the red.xml file after I added it, link continue to work till next restart of eclipse...

**Comment by michalanglart** [comment]
Once the file was there it was loaded into memory so all the features which somehow required to have this configuration loaded were working until you've restarted RED. 

This behavior can be probably fixed by loading some default project configuration when red.xml is not there. I'll open the issue for this in our internal issues tracker.

However as I stated before: as of now this file is important for RED, maybe we could make it less important in future but I cannot say how near/distant this future is.

**Comment by Galgc** [comment]
Ok. Thanks! 
at least I have a good enough workaround for now (add the red.xml file and set git to ignore it).
