### ISSUE TITLE
Why "Insert Cell" menu always disabled?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#136]
I found there is a "Insert Cell" command in context menu, but it is always disabled.

How can I make it works?

**Comment by michalanglart** [comment]
Hi,

I've checked it and it looks that in version 0.6.5 it was working however in next release (0.7.0) it didn't, so overall it was unnoticed for over a year...

**Comment by Pantyhose-S** [comment]
so will it be fixed in next version?

**Comment by michalanglart** [comment]
We'll see - if this is just disabled then we surely can enable it in next version. On the other hand given the fact that it stopped working between 0.6.5 and 0.7.0 where tables were actually implemented I suspect that it may be simply not implemented yet. If that's the case then 0.8.1 would be the target since we are currently pushing last things before 0.8.0 release and we don't want to delay it even further. 

However you can expect that period between 0.8.0 and 0.8.1 will be much shorter than current period after 0.7.9, so overall I would say that this may be implemented and released within 6-8 weeks.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
