### ISSUE TITLE
Unable to launch RED on Java 9

### ISSUE THREAD

**Issue by lolotoms** [nokia/RED#137]
Hi,

I just installed the appium environnement to run tests on iOS 11:
- OSX 10.13
- Python 3.6
- Java 8

When I launch RED, I select the workspace and then an error occurs:

![image](https://user-images.githubusercontent.com/13163619/30761638-3c621e3a-9fdf-11e7-9cb0-a6a33deb7075.png)

and I don't really understand the logs:

[logs.txt](https://github.com/nokia/RED/files/1325628/logs.txt)

It worked fine with OSX 10.12.6. Do you have an idea please?

**Comment by michalanglart** [comment]
Hi, are you sure it is running on Java 8? In log file there is a line saying java.version=9. 

Given the fact that today Java 9 was released it looks like it was maybe automatically updated?

If that's the case then:

- we haven't tested RED with Java 9
- Java 9 introduces new modules system called Jigsaw which may have problems loading classes from osgi based eclipse platform
- probably you need to adjust the way Java is launched by changing eclipse.ini or RED.ini file

I have only my mobile with me for whole weekend so I'm not able to check it now, but you may google for 'running eclipse on Java 9' in order to see what is needed. I'll be able to help on Monday.

Unless it is really running on Java 8, then I have no idea as of now...

**Comment by lolotoms** [comment]
Hi michalanglart , you are right ! I firstly installed java 9, and when red crashed, i installed java 8 and change java environment variable. I don't understand why there still have link to java 9. I deleted Java 9 folder and now, red start without error.

Thanks for your answer !

**Comment by michalanglart** [comment]
Good to hear it does work!

We'll have a look into running RED on Java 9 and put some info about it here and in next release notes.

**Comment by michalanglart** [comment]
In order to run RED on Java 9 the RED.ini file has to be edited (or eclipse.ini if you're using eclipse with RED installed as a feature).

- First of all you may add `-vm path_to_java_vm` option to point to Java 9 executable (although you may have it in your PATH environment variable)
- secondly the virtual machine should have `--add-modules=ALL-SYSTEM` argument passed

Overall your RED.ini file should contain this:
```
--launcher.appendVmargs
-vm
C:\Program Files\Java\jdk-9\bin\javaw.exe
-vmargs
--add-modules=ALL-SYSTEM
```

First line is telling RED/eclipse to append arguments for Java instead of overriding them, lines 2-3 are telling where the Java executable is located (here under windows) while the arguments after `-vmargs` will be passed to Java virtual machine and it is crucial to have `--add-modules` argument passed.

**Comment by michalanglart** [comment]
Version 0.8.9 should work properly on Java 8/9/10/11
