### ISSUE TITLE
Could you explain how to config output, log and report to specific folder

### ISSUE THREAD

**Issue by castiny** [nokia/RED#139]
If I have folder results and i need storing output, log and report to that folder. I try create external tools configuration by set location working directory and arguments as show as below
1. Location
C:\Python27\Scripts\robot.bat --outputdir results --timestamp
2. Working Directory
E:\AutomatedTesting\RobotFramework\Web\DemoEclipse\DemoRED
3. Arguments
"${selected_resource_loc}"
 but i got message 'Launching Robot' has encountered a problem. The file does not exist for the external tool named Robot'

Thank you very much

**Comment by michalanglart** [comment]
Hi,

With RED we do not launch tests using 'external tools configuration' and we are not aware if any user does this. The simplest workflow is that the project containing Robot test suites is imported or created in RED and then one use Run -> Run as or Run -> Debug as on the suites which needs to be launched. 

Within those launches 'Additional Robot Framework arguments' can be specified where you can pass arguments in order to specify output directories. Please take a look at our help system (either in RED: Help -> Help System -> RED - Robot Editor User Guide; or here at github: http://nokia.github.io/RED/help/). Since it seems that you are using custom batch script you may be specifically interested in Launching Tests / Local launches scripting topic.

Feel free to ask if something is not clear still.
