### ISSUE TITLE
How to set git project as RED project ?

### ISSUE THREAD

**Issue by gjemp** [nokia/RED#14]
I imported old test project from git. Now i wanna set it as RED project , but was not able to find a way how to do it. Documentation did not contain any information how to configure the builder in project properties. Creating red.xml did not help me out also :) Any idea how to fix my question :)

**Comment by adam-wypych** [comment]
Hi,

are Your old project was made with RED or is just pure Java/Eclipse project with RobotFramework test cases inside?

**Comment by michalanglart** [comment]
Hi,

in order to see project as RED project it have to be configured to have proper nature and proper builder. Each project created in eclipse should contain ".project" file inside, which is a xml document containing some metadata. RED will see the projects as its own, when it Robot nature and Robot Libraries builder are defined inside. The file .project should contain following xml fragments:

		<buildCommand>
			<name>org.robotframework.ide.eclipse.main.plugin.robotLibrariesBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>

inside <buildSpec> tags and:

		<nature>org.robotframework.ide.eclipse.main.plugin.robotNature</nature>

inside <natures> tag. Currently there is no way to add those entries to existing .project file without editing them manually. Newly created RED projects (using New -> Robot project) contain those entries, so you can always create new one and see how the file should look like.

If you can't see .project file in your project then it may be filtered out from view. Click on triangle in top of Project Explorer view, then on "Customize view..." menu. If you have ".* resources" option checked please uncheck it and .project file should appear in your project.

Hope this helps!

**Comment by gjemp** [comment]
Hi, 
actually it is a clean project - not a java or RED. So no .project file also :) But , no idea what i did, but now the project has PyDev Builder and is able to work same way as RED project :) I also copied red.xml and libs to my project .

**Comment by gjemp** [comment]
PS! i still had the .project and updating it with michalanglart  suggested data it made my world look 10 times better :) thanks !
