### ISSUE TITLE
Update Site Error

### ISSUE THREAD

**Issue by justinclagg** [nokia/RED#142]
Hello,

I am receiving errors using the update site (http://master.dl.sourceforge.net/project/red-robot-editor/repository) for clean installs and updates. For installation the error is:
```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://master.dl.sourceforge.net/project/red-robot-editor/repository/0.8.0/plugins/org.robotframework.ide.eclipse.main.plugin_0.8.0.201710041029.jar.
Premature end of Content-Length delimited message body (expected: 9981866; received: 5535419
```

**Comment by KrzysztofJozefowicz** [comment]
Hi
I just tried with clean Eclipse Oxygen (Java IDE), RED installed without a problem. 
Please try again, it may be a network problem your ISP or Sourcefofge. 
If you will still face this issue, you can install/update RED using RED_feature.zip:
[https://github.com/nokia/RED/releases/download/0.8.0/RED_feature_0.8.0.201710041033.zip](https://github.com/nokia/RED/releases/download/0.8.0/RED_feature_0.8.0.201710041033.zip):
1. download RED_feature.zip file
2. From **Help->Install New Software** select **Add -> Local** - and select downloaded file
3. Proceed with installation

**Comment by justinclagg** [comment]
Thank you for the response. I was able to successfully install on a third machine. I originally tried two others on different networks. 

I will follow up if I'm able to determine a reason. I'd like our users to use the update functionality if possible, rather than manually adding the feature. 

Thanks again!

**Comment by KrzysztofJozefowicz** [comment]
If your setup requires update site,you may also mirror RED update site and run it on local web server. This can be useful for hosts which are separated from internet due to internal policies.
Have a look at: [https://wiki.eclipse.org/Equinox_p2_Repository_Mirroring](https://wiki.eclipse.org/Equinox_p2_Repository_Mirroring)
Mirrored UpdateSite can be placed in web accessible folder on web server,

I will mark this case as closed,if you will have any more question please ask.
