### ISSUE TITLE
self define run command argument

### ISSUE THREAD

**Issue by lalamini** [nokia/RED#143]
Hello, all
    I meet a problem,

    I want run the command like this (in ride)

    /usr/local/bin/pybot --variable zzz:ios --variable capture:1 --variablefile public/var.py

    that mean use pybot , use two vairables and one variablefile.

    but it can not configure correctly in RED

   everytime ,it runs like this:

   /usr/local/bin/pybot --variable zzz:ios --variable capture:1 --variablefile public/var.py /usr/bin/python -m robot.run --listener /var/folders/9w/9qjhzf411bj74p9fnjn9t6j40000gn/T/RobotTempDir3386043211270458870/TestRunnerAgent.py:59957 --argumentfile /var/folders/9w/9qjhzf411bj74p9fnjn9t6j40000gn/T/RobotTempDir3386043211270458870/args_c2ea58be.arg /Users/xxxxx/xxxxx/xxxxxxx 

  it seems that I cannot remove the command "robot.run" in you system, so , could you tell me how  I can add my variables and variablefile in my test case run argument with you system command "robot.run" or I can remove the system command "robot.run"?

**Comment by KrzysztofJozefowicz** [comment]
Hi
"pybot" is a system wrapper for python -m robot.run , you can verify it by looking the content of pybot:
`cat /usr/local/bin/pybot`
RED does not use pybot to execute tests,it uses python module robot.run (that's why the command line includes _python -m robot.run_). 
I got the feeling that you may unintentionally misconfigured RED for your purpose. Let's start from beginning:
 
1. Let's ensure that you have proper RobotFramework and Python set. Check Window->Preferences->Robot Framework -> Installed frameworks - there should be at least one entry with black color stating about Python & Robotframework installed in system. If not select Discover or point to python executable (most probably under /usr/bin) using Add.. button.

2. As you need to pass `--variable zzz:ios --variable capture:1 --variablefile public/var.py` to RobotFramework you can do it in 2 different ways:
    - include variables with values zzz and capture into variablefile public/var.py and include it in red.xml (double click on red.xml to open editor) under Variable files,it will be automaticly pass on every execution
   - you may pass `--variable zzz:ios --variable capture:1 --variablefile public/var.py` to Robot directly.  From Run topmenu select Run Configurations...,select the one configuration which you will use,in Robot tab fill in Arguments in Additional Robot Framework arguments,Apply&Close.
To use this configuration to execute tests,select test suite,from right-click menu select Run As. 
![image 1](https://user-images.githubusercontent.com/3999733/31767019-eadee12e-b4c9-11e7-8723-6a4142dcd722.png)

   - additionally, you can configure RED to pass your arguments to every executions,you can find relevant option under **Window->Preferences->RobotFramework-> Launching -> Default Launch Configuration** with Additional Robot Framework arguments field.

Verify this by running test and checking what is the content of argument file (it is generated per test run, from your example `--argumentfile /var/folders/9w/9qjhzf411bj74p9fnjn9t6j40000gn/T/RobotTempDir3386043211270458870/args_c2ea58be.arg`). 
It should look like 

``` 
# arguments automatically generated
--pythonpath   D:\workspace\new
--suite        New.Test
# arguments specified manually by user
--variable     zzz:ios
--variable     capture:1
--variablefile public/var.py
```
By default RED wraps arguments pass to Robot into argument file to not make command line to long,this can be changed in Windows->Preferences->Robot Framework -> Launching ,unselect option: _Pass Robot arguments using arguments file_

**Comment by lalamini** [comment]
Wow that's great, I will try to set them in RED.xml directly, 
Let me try it!
Thank you so much for give me so detail answer!!!
I like the RED tools!
