### ISSUE TITLE
The editor will report exception when script has lots of errors.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#152]
I have a script about 600 lines, and it contains about 400 errors and warnings(some library not imported, missing lots os keywords).

there will be something strange:
when I select lots of text, sometimes the editor will report a java null exception.
when I drag the scrollbar, sometime it won't stop at the right place.

and also, the editor will be very slow when there are lots of errors in script.

**Comment by michalanglart** [comment]
Hi,

we would need to investigate that. 

As to the null pointer: can you please attach the stacktrace?

As to the performance of editor for file with hundreds of errors - I think this is quite likely that this may be caused by the eclipse platform itself - the source editor may be not optimized for such situations. For example in JDT (java support for eclipse) by default up to 100 problems are reported for single file (see Preferences -> Java -> Compiler -> General -> Maximum number of problems reported for single compilation unit). We'll see but maybe the only way is to introduce similar limit.

**Comment by KrzysztofJozefowicz** [comment]
If you have a long script with lots of errors and you can leave with them,you may consider to exclude this file from validation. Click on file in Project Explorer,from RMB -> Robot Framework menu -> select Exclude from validation

**Comment by Pantyhose-S** [comment]
As to the null pointer: can you please attach the stacktrace?

Last time I seen this exception, there is no stacktrace printed.
Next time I will take a photo.

Sorry, my company  computer can not connect to internet.

**Comment by michalanglart** [comment]
Ok i see. 

If you haven't changed or deleted your workspace then this exception should be logged inside .log file located in metadata folder of your workspace
