### ISSUE TITLE
Eclipse will run out of memory when run a long time script

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#164]
My script will run for 72 hours, and it will output lots of messages.

And when it runs about 5 hours, eclipse will crash by out of memory exception, maybe some of the views, like the message view takes the memory?

**Comment by Pantyhose-S** [comment]
By the way, the first error shows "An internal error occurred during:Agent connection server. Java heap space", then eclipse shows it out of memory.

**Comment by michalanglart** [comment]
Hi,

We've recently had issue reported for message log view running out of memory in #149 

In 0.8.1 we have removed data from previous launches (as it is currently not possible to see previous launches messages in the view anyway), we've added a button which clears the view and possibility to limit buffer for message log view. By default it is unlimited but it may be changed in Preferences -> Robot Framework -> Launching.

If limiting the output or manually clearing the view does not help then maybe it is something different leaking. In such case it would be very helpful if you would provide us a heapdump. In order to do this please add

`-XX:+HeapDumpOnOutOfMemoryError`

argument to `RED.ini`. Just make sure it is added after `-vmargs` switch because this is an argument to virtual machine. Once RED crashes with out of memory a heapdump file will be created in main Red directory. It is compressing well, so zip it and send it to us for analysis.

**Comment by michalanglart** [comment]
@Pantyhose-S do you still experience out of memory errors?
