### ISSUE TITLE
Zoom in And Zoom out not working with Red installed?

### ISSUE THREAD

**Issue by MarkLunding** [nokia/RED#167]
I recently switched to Eclipse Oxygen and Red 0.8.x.
When i want to use the text zoom options of Eclipse ([ctril]+[+]) they don't work.

When i download a clean eclipse (oxygen.1) it works. Install Red and use the robot perspective once, and the zoom option no longer works. 
Using windows 10 Pro build 16299, eclipse Oxygen.1a Release (4.7.1a), and Red 0.8.2.201712181236

**Comment by KrzysztofJozefowicz** [comment]
Thanks for info, zooming is indeed disabled in Source and Table editor, we will look into your request to enable text zooming (at least Source is doable,for Tables together with text size,column size should also be resized).
For now, text size in Source can be changed from **Windows->Preferences->General->Appearance->Color and Fonts** under category Basic -> Text Font

**Comment by MarkLunding** [comment]
@KrzysztofJozefowicz Thanks for the quick reply.
I'm using the zoom option because i sometimes give demo's. The zoom option is a very powerfull help. It would very helpfull if at least in source this is working.

**Comment by KrzysztofJozefowicz** [comment]
ok,lets start with text size in Source then.

**Comment by michalanglart** [comment]
Chaning font size with Ctrl+/- was working in all REDs between 0.7.0 up till 0.8.0 (inclusively). 

It started working in 0.7.0 because of platform switch from Mars to Neon (the feature was implemented in Neon).

Then it stopped working in 0.8.1 because of platform switch from Neon to Oxygen (because of a bug introduced in oxygen with change for: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512571 )

It is going to be fixed in upcoming eclipse Photon (release at the end of june 2018) with change for: https://bugs.eclipse.org/bugs/show_bug.cgi?id=518939

However we will provide a workaround in order to make it work in RED again until it will be released using Photon platform (probably Q3/Q4 of 2018)

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.3
