### ISSUE TITLE
Is there anyway to split html log to small files?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#171]
I will run I big launch every weekend, include about 30 folders with 500 testcases.
So I will get a very big html log file on monday, It is hard to open/analyse it.

Now I split the big launch into small launchs, and create a launch group to split the log file into small files. 

Is there anyway to do it automaticly? Just like a checkbox, when checked, every folder will create a single html log.

**Comment by michalanglart** [comment]
According to Robot Framework User Guide you can split the log file: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#splitting-logs

In order to do this via RED you have to add `--splitlog` argument into `Additional Robot Framework arguments" field of your launch configuration (this is described here: http://nokia.github.io/RED/help/user_guide/launching/local_launch.html )
