### ISSUE TITLE
RED to support .venv site-packeges

### ISSUE THREAD

**Issue by Formartha** [nokia/RED#173]
Hi,

We're working on venv for installing python packages as well as Robot's.
While trying to build the project in red.xml, we found out that RED can't handle hidden folders for building the reference path is broken.

How can RED support it?

Thanks,
Mor

**Comment by michalanglart** [comment]
Hi,

are you able to share some minimal project and configuration which would show us this issue?

Basically RED omits hidden resources (the ones starting with dot character) when building & validating for performance reasons. We consider such resources not be the part of the project but some metadata.

For example when project is version-controlled using svn then every single level in project tree contains .svn folder with metadata and browsing trough those hits the performance.

**Comment by Formartha** [comment]
Thanks for taking the time and replying back.
However, since we have a different approach for working with python projects - I sense that there's a need for it.

So, we are building our environment with using venv (http://docs.python-guide.org/en/latest/dev/virtualenvs/). The reason for doing it is because we run a lot of projects on the same developer’s station + using Jenkins slaves for multiple projects. So, considering that, we need to have an environment which won't be affected by any python package changes and installations.

In our project, we created a script to instantiated the python virtualenv and pointing RED to it (by adding the evnv python lib to the project interpreter). But, once viewing the RED.xml file, we saw that it breaks due to the fact that it can't handle  ./folders.

Please see the attached screenshot

![image](https://user-images.githubusercontent.com/8232832/34957433-49068a7a-fa36-11e7-9831-46e0f9bb9cae.png)

**Comment by Formartha** [comment]
Hey,

There is other issue that occurs due to red.xml isn't supporting the .venv project files. 
While trying to view Robot Referenced libraries and clicking on "show library source", the eclipse (RED) fails to find the source package with error message "Empty location path!"

This is crucial for us to continue developing and not skipping the marvelous ability of using python virtualenv.

**Comment by michalanglart** [comment]
Hello,

I've just played a bit with this.

1. I've only used `virtualenv` till now and didn't know how `venv` works exactly, so earlier I've assumed that it somehow creates and uses `.venv` directory(ies), but that's not true. This folder is there because you/your script have chosen this name to be the folder where virtual environment should be created, right?

2. I've created virtual environment in a directory called `.venv` and tried to play with it in RED; installed `RequestsLibrary`. I've added the path to python executable inside `.venv/Scripts` in RED preferences; created a project with a suite importing `RequestsLibrary`. It properly recognized the library, it was added to red.xml. I was able to see the keywords inside it etc. Found no problems with that simple scenario, library source is also opening properly.

Is your `.venv` directory a part of project?

**Comment by michalanglart** [comment]
Once I created virtual environment inside the project and libraries were auto-discovered I've run into following issue:

Validation was saying that: `Missing library file 'project/.venv/lib/site-packages'. Keywords from this library will not be accessible`. Despite that I was able to see those keywords in content proposals and validation also did not raised any issues about those keywords. However this error is also visible when I use `venv` directory instead of `.venv`. This error however is gone when I change `lib` part in path to `Lib`. This mean that autodiscovery should return case-sensitive path while it didn't.

The only point in which we check for hidden directories (ones starting with dot) is when validation analyses where it should look for the files to validate and it omits those with dot. This mean that incorrect behavior would occur if you would keep .robot files inside the hidden directories. We will not analyze them and hence no errors/warning will be generated for them.

As of now the only issue I've found when trying to replicate your problems is with those case-sensitive paths. I don't know however if those are the same problems. Can you please expand on:

> we found out that RED can't handle hidden folders for building the reference path is broken.

so it would be easier for us to look for the behaviors you found unexpected?

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.3
