### ISSUE TITLE
Is there anyway to auto rerun testcase if it fails?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#175]
My testcase sometimes will fail by network timeout or other temporary reason, if I run it again, it will pass, and I think this is ok.

So when a testcase  fails, I want it will be auto rerun by eclipse/red. The options are:  rerun times(0~3)、when to rerun(immediately or after all testcase done)
if the testcase rerun pass, it will report as pass.

Is there anyway to do this?

**Comment by michalanglart** [comment]
Hi,

no there is no such functionalityin RED.

Theoretically you may want to dig into RF Listener API version 3 (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-version-3 ) which allows to dynamically modify suites/tests, however I doubt it will allow to e.g. duplicate test case just after it was executed.

**Comment by michalanglart** [comment]
> Listerner doesn't has possibility to modify running suites - it is the job of SuiteVisitor (see:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id667 ).

To make it clear: Listener API 3 does allow to modify execution/results on the fly as seen here on examples: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#modifying-execution-and-results - there is an example which adds a test to each suite before it starts and keyword to each test before the start. However as stated:

> Trying to modify execution in end_suite or end_test methods does not work, simply because that suite or test has already been executed

so it is not possible to e.g. clone failed test on end_test event and add it to parent suite, so that it would be executed once again.

**Comment by adam-wypych** [comment]
Ok, I see nice that RF removes requirements for separate `SuiteVistor` and `TestExecutionListener`, but I think still you need to use `--rerunfailed` and `--merge` to achieve re-run failed tests and proper output.xml and logs.

**Comment by michalanglart** [comment]
Yes, for sure. 

Seems that even Listener API 3 does not help here, so @Pantyhose-S you may want to try follow @adam-wypych script from above.
