### ISSUE TITLE
Resolving variable set with EXECDIR in virtual mapping results in error

### ISSUE THREAD

**Issue by GerwinLaagland** [nokia/RED#190]
Hello again. With the last version of the RED plugin I've seen some good improvements. Unfortunately, the enhancement that was implemented with https://github.com/nokia/RED/issues/155 doesn't function entirely correct.

**Resource file:**
> *** Variable ***
> ${LOG}    This is a message.

**Testscript:**
> *** Settings ***
> Resource    ${RESOURCE}
> #Resource    ${EXECDIR}${/}Resource.robot
> 
> *** Test Cases ***
> Test Execution
>   log    ${LOG}

Virtual mapping contains:
![vm-red](https://user-images.githubusercontent.com/8427040/36899917-1ec7e93c-1e19-11e8-993c-9f95525fb922.png)

**When executing test:**
> Suite Executor: Robot Framework 3.0.2 (Python 2.7.12 on win32) 
> 
> [ ERROR ] Error in file 'C:\ws\VM-EXECDIR\Testsuite.robot': Replacing variables from setting 'Resource' failed: Variable '${RESOURCE}' not found.

Validation works perfectly fine in the eclipse editor. Upon testexecution the variable is not correctly added however, causing the above issue.

Edit: Added a few project files for more information. Apologies for the edits.
[VM-EXECDIR.zip](https://github.com/nokia/RED/files/1775204/VM-EXECDIR.zip)

**Comment by michalanglart** [comment]
Hi,

it never worked that way. Those variables are not added when executing tests. Variable Mapping is a mean to tell RED: 

"Hey RED when I'm running my tests I'm injecting variable ${RESOURCE} with value 'VALUE' so please be so kind and take it into account when resolving and analyzing imports'

which is different than:

"Hey RED this is a variable ${RESOURCE} with value 'VALUE' - be so kind to use this value when resolving import and please also tell Robot about this variable when executing tests'

Which means that you also have to somehow tell Robot about this variable (inject it globally via command line, via variable files, define somewhere in your project etc.).

We could probably use data from Variable Mapping and always provide those variables to Robot when running tests from RED. This could however make setting up CI environment harder on such project because CI would run tests directly through Robot Framework which is of course not aware of red.xml.

**Comment by GerwinLaagland** [comment]
Aha! I see. I apologize for misunderstanding then. If the goal of variable mapping is merely to provide a temporary 'guide post' so as to analyse whether code is correctly implemented then you may close this issue. 

Having looked at it again. I've now declared the item in a python variable file like so:

``
