### ISSUE TITLE
Tests and resources unaware of variables created by initalization file

### ISSUE THREAD

**Issue by realchrisolin** [nokia/RED#195]
I'm hoping this screenshot illustrates the issue as I'm having difficulty describing it with words. The only workaround I've come up with so far is to declare the variables in the test. I'll still get a warning because RED thinks they're unset, but least it's better than an error.

![image](https://user-images.githubusercontent.com/1288116/37791877-ac46ba78-2de0-11e8-838f-6fad5e0ae0a6.png)

**Comment by adam-wypych** [comment]
your issue is the same as described in #68 . RED as editor base on idea that we collecting variables, keywords base on dependency. In other words we do not import variables base on execution flow from `__init__` files.

**Comment by michalanglart** [comment]
Hi,

I would suggest you to use the workaround described by @adam-wypych here: https://github.com/nokia/RED/issues/7#issuecomment-181882452. You wouldn't see any warnings or errors with such setup (pythons variables file attached via red.xml).

I will write a bit longer comment here on that matter so that I could reference it in future in case the issue will reappear :)

In the tickets mentioned above (#7 and #68) the comments briefly describes why supporting this is a problem. RED performs [static analysis](https://en.wikipedia.org/wiki/Static_program_analysis) while in your case the variables are created dynamically during execution. This is a very different story because in general we do not know whether this code will be executed or not. It may depend upon tags assigned to test or the root suite from which the tests are started (i.e. you may start the tests from suite below your `__init__.robot` file so that it will not be executed at all).

I don't want to go into the computational theory too deep but this problem crosses the boundary of what is possible to compute and what is not. The thing is that the problem I've mentioned above - checking whether some part of code will be executed or not is [undecidable](https://en.wikipedia.org/wiki/Undecidable_problem) which means that there is no such algorithm which can always provide us with the answer. 

In RED only local variable assigning is somehow implemented. Given for example:
```
* Test Cases *
test
    ${x}=  Set Variable  42
    Log  ${x}
```

RED will not generate any errors in second line of test because it has this very simple heuristic implemented: when seeing a variable assignment inside body of test case or keyword we assume that it will be defined and visible in next lines. However this is only a heuristic and in general it is wrong. Consider for example this program:
```
* Test Cases *
test
    ${limit}=    Set Variable    1
    :FOR    ${i}    IN RANGE    ${limit}
    \    ${x}=    Set Variable    42
    Log    ${x}
```

RED will not generate any errors and if you would run it would pass. However change `1` into `0` in `${limit}` assignment and the body of loop will never be executed so the test would fail due to missing variable. But RED never warns about this! It happens because of the fact that deciding whether the loop will execute anything inside it or not is again an undecidable problem.

Of course being undecidable is not that bad thing after all. For example the problem of parsing C++ code is known to be undecidable ([blog post](http://blog.reverberate.org/2013/08/parsing-c-is-literally-undecidable.html)) yet there are many C++ parsers working out there and most people use them without even knowing that their parser may hang infitely or crash at some point for some valid C++ programs.

What we could possibly do with all those `Set Local|Test|Suite|Global Variable` issues is to provide more heuristics which would more-or-less cover most of users cases however given the fact that so far for most of those users the workarounds with e.g. variable files are working quite well we are reluctant to do it.

**Comment by realchrisolin** [comment]
For what it's worth, I did search through existing issues before opening this ticket and didn't get any hits from the keywords I used. These replies and the suggested workaround helps. I'll leave it to you to figure out if this is an issue you want to accept or close it out due to the technical limitations involved.

**Comment by michalanglart** [comment]
I'm closing this ticket for now
