### ISSUE TITLE
Argument file and selecting a single test case 

### ISSUE THREAD

**Issue by p74** [nokia/RED#212]
I Am currently moving from ride to red ... so I new with eclipse and red... so far I can run my tests and set a breakpoint in robot code 
But how can I setup red to run a single test and use a default set of arguments or in my case a default argument file instead of putting every time the arguments by hand 

Second how can I set a breakpoint in python? in robot code it's working.

Is there a good reference manual or usefully tips and tricks page  for red ? 

Thx

**Comment by michalanglart** [comment]
Hi,

there is a RED Help which is available from application: `Help -> Help Contents -> RED - Robot Editor User Guide`. It is also available online at http://nokia.github.io/RED/help/

There is a chapter `Debugging Robot & Python with RED & PyDev` (http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html) which describes the way python code can be debugged together. However it may work a little bit differently than you seem to expect. RED itself is only able to debug robot code but it is possible to combine RED debugging session with PyDev debugging session in order to achieve that goal. Please refer to help topic.

Single tests can be run by clicking on them with right mouse button and chosing `Run` either in Project Explorer or from editor too. 

Default set of arguments added to every launch configuration is possible to be defined in preferences and it is also briefly noted in user guide: http://nokia.github.io/RED/help/user_guide/launching/launch_prefs.html#default-launch-configurations

**Comment by p74** [comment]
Thx for your help I will look into this

Greetings from the Netherlands

Op di 22 mei 2018 13:31 schreef michalanglart <notifications@github.com>:

**Comment by michalanglart** [comment]
Seems that nothing more can be done in this issue. Closing
