### ISSUE TITLE
How to add libdoc (xml file) in java library (.jar)

### ISSUE THREAD

**Issue by rumensoft** [nokia/RED#218]
I have .jar library, that contains method with documentation. Here is example:

```
/**
 * This is regular calculation
 * 
 * @param x		Number X
 * @param y		Number Y
 **/
public class CalculateSum {
	public int calculator(int x, int y){
		int z = x + y;
		return z;
	}
}
```

After that, I export it into runnable .jar. I added the .jar in red.xml file, like Java library. So far so good. I have access to the keyword. But, the documentation is missing:
![calc](https://user-images.githubusercontent.com/39481469/40722543-49344722-6425-11e8-8d57-4baf9a2cbb42.png)

**Q1:** Why the documentation from the Java method doesn't shows?

**Q2:** how I can put the generated documentation in .jar file?
If I run this command: `jython -m robot.libdoc --version 1.0 CalculateSum.java CalculateSum.html` will generate me, documentation.

**Comment by michalanglart** [comment]
Hi,

we need to check it but as of now: RED is generating documentation using `robot.libdoc` but library name is passed with properly augmented `PYTHONPATH`/`CLASSPATH` variables so that libdoc is able to find the classes. It means that in your case RED will try to use `libdoc` on `unitTests.CalculateSum` library with path to the jar file added to `CLASSPATH`. Since probably there are only compiled `*.class` files in your jar it will not see the comments.

I'm about to leave the office for couple of days so I will be unable to check it now but you may try if it would work once there are sources packaged in the jar file. 

If you're able to generate documentation by yourself then in `red.xml` file you can also add so-called `Virtual library`: this is simply the XML file which you can generate with `libdoc` tool (add `--format XML to your command and save it to file; then add in red.xml as virtual library).

**Comment by adam-wypych** [comment]
Answers:
**Q1** - Java compilator removes comments from generated bytecode. Therefore executing libdoc over `class` file, will always result in missing comments. 

**Q2** - If you are using maven you can include generation of libdoc into your maven process ( http://robotframework.org/MavenPlugin/libdoc-mojo.html ) and then as @michalanglart said include generated XML into your RED configuration. As I see is not currently possible to put as library XML location path inside JAR file, so it need to be somewhere outside.

I've been tried to include in `red.xml` file a location as `jar:file` but it gives me just `NullPointerException`:
` 
<referencedLibrary type="VIRTUAL" name="SwingLibrary.xml" path="jar:file:/C:/Users/Adam.Wypych/Downloads/SwingLibrary.jar/SwingLibrary.xml"/>
`
It will be nice to have possibility to include `VIRTUAL` libdocs not just from real location but also from JAR/ZIP files.

**Comment by rumensoft** [comment]
Today I made more tests and saw that there is trick and the documentation works!

1. FIRST Import .xml file like libdoc
2. THEN Import .jar file like java librar

**Comment by adam-wypych** [comment]
I think its stay in memory, so after restart you will need to do trick again, but as workaround for one run it should works :) Anyway more cleaver solution will be highly appreciated :)

**Comment by michalanglart** [comment]
I'm closing this since there is a follow-up issue #219 for providing possibility to point libdoc file in zip/jar
