### ISSUE TITLE
Allow to programmatically convert projects into test projects

### ISSUE THREAD

**Issue by planger** [nokia/RED#222]
In our own plug-ins, we would like to be able to "programmatically" convert a project into a test project. However, the `org.robotframework.ide.eclipse.main.plugin` doesn't export any packages, so we can't use the `org.robotframework.ide.eclipse.main.plugin.project.RobotProjectNature`, and the handler for the command `org.robotframework.red.configureRobotNature` is only active and only works if a project is selected, so we can't invoke the command via the Eclipse handler service.

Thus, there is no clean way of doing that at this moment. Exporting the package `org.robotframework.ide.eclipse.main.plugin.project` would solve this problem. Would you be ok with a PR that exports this package?

Alternatively, we could introduce a new command, similar to `configureRobotNature` that has an always active default handler, which will convert the project specified in a command parameter.

Thanks a lot!

Maybe related: #113

**Comment by michalanglart** [comment]
Hi,

sure - we're definitely ok with PR exporting this package in plugin manifest. 

I guess it's the highest time to establish some API, hide internal code in `*.internal.*` packages and export  reusable components so that they can be used by other plugins. We were talking about this when #113 was raised but no one asked about this since then and we were occupied with different topics, so nothing was done.

If you have other requirements and wishes for RED API (code as well as extension points) feel free to share them with us.

Out of curiosity (if that's not a secret of course): what are you building with RED?

**Comment by planger** [comment]
Thanks a lot for your speedy reply! I opened a PR to export the package containing the `RobotProjectNature`.

> If you have other requirements and wishes for RED API (code as well as extension points) feel free to share them with us.

For now, I think we are good with just this package. If we have more requirements, I will come back to you. Thanks a lot!

> Out of curiosity (if that's not a secret of course): what are you building with RED?

We are just integrating the RED plug-ins in a proprietary tool to include its features.

**Comment by planger** [comment]
Closed with #223 

Thanks a lot for the speedy merge!
