### ISSUE TITLE
Variable should exists issue

### ISSUE THREAD

**Issue by MichaelFriis-Github** [nokia/RED#224]
Thank you for contributing with an editor that is maintained, finally making the switch from RIDE.

In some cases, i execute the test scripts through the command line, with argument variables. I want to check if a variable is set through the command line or not. 
See picture
![image](https://user-images.githubusercontent.com/6860060/41292849-fd6e6712-6e53-11e8-86b4-9666e2efab84.png)

As the ${cmd_arg_pss_ip} variable, is only set through the command line, RED underline the variable as: - "Variable 'cmd_arg_pss_ip' is used, but not defined" error, which is correct, as it is only defined through a command line argument. 
Is there any way i can make this error stop, when using the above solution?

**Comment by adam-wypych** [comment]
you can define it in red.xml as variable mapping: http://nokia.github.io/RED/help/user_guide/working_with_RED/variable_mapping.html

**Comment by KrzysztofJozefowicz** [comment]
Alternativelly, you can create simple variable file with list of comman
line vars and include it in red.xml under Variable Files section. In this
case, when ever running test, such variable dile will be used as command
line option.

wt., 12.06.2018, 15:31 użytkownik adam-wypych <notifications@github.com>
napisał:

**Comment by michalanglart** [comment]
Hi,

`Variable Mapping` will not help you unfortunately @MichaelFriis-Github . Variable mapping only works for parameters used in `Resource`, `Library` and `Variables` settings - apart from those places RED never tries to resolve variables when analyzing source. Historically it was introduced because we didn't wanted to resolve variables values (since they are runtime in nature) however imports were often parameterized sow we had to provide some mechanism capable of handling them. Otherwise RED would not be able to see lots of keywords/variables etc.

I'm not sure if defining variable file is a way to go. Basically your code looks like this in more C-like pseudocode:

```
PSP_IP = ...
if (isDefined(cmd_arg_psp_ip)) {
   PSP_IP = cmd_arg_psp_ip;
}
```

where `isDefined` returns true when `cmd_arg_psp_ip` exists. This mean however that if you will include some variable file in red.xml with `cmd_arg_psp_ip` defined then it will be always included when running tests so `PSP_IP` will be always overridden when running tests from RED (since it will always exist). So it's up to you @MichaelFriis-Github if that's acceptable.

However: do you need such logic anyway? I only see very small snippet regarding `PSP_IP` variable usage but it seems that under some circumstances you may take advantage on variables scopes and priorities. As described in RF User Guide (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-priorities-and-scopes) variables passed in command line are in global scope accessible from anywhere and have priority. As an example:

```
*** Test Cases ***
case
    Log    ${MYVAR}
*** Variables ***
${MYVAR}    1
```

running: `python -m robot.run suite.robot` outputs: `1`
while: `python -m robot.run --variable MYVAR:2` outputs: `2`

Pretty much similar effect but without checking variable existence etc. Although as I said: this may work differently than your logic somewhere else outside of this small code snippet.

As to the issue itself:
There is no way to tell RED "I don't want to have error of this type in this line`. Suppressing errors is a recurring topic however up to the date we've only implemented global settings for certain problems categories. In preferences you can change the level of marker (error/warning/info/none) created for problems belonging to some category of problems. This is not really interesting in your case because you will switch off markers for some real problems.

Next version which is about to be released in next days will not raise an error in this case for variable ${x}:
```
case
   Variable Should Exist   ${x}
```
however you're using it inside `Run Keyword And Ignore Error` so it will be still visible. However such constructions nested in `Run *` keywords family will be validated soon (but probably not in next version; it is raised in #28). 

Overall in your snippet only second error will remain when both #96 and #28 will be resolved (0.8.6 and probably 0.8.7 respectively). However I don't have good solution with the second error marker apart from implementing local errors suppression.

**Comment by adam-wypych** [comment]
@michalanglart I think this is very interesting, what you wrote about special treatment of `Variable Should Exist`, because base on the domain in which some of keywords exists, this keyword and `Run *` are very close to each other. The main relation between them exists in special treatment of their arguments, the difference is only related to action which need to performed (in `Variable Should Exist` is suppress error or as in `Set Variable If` create new variable; and in `Run *` treat during validation some arguments as keywords). So, I can imagine the keyword, which internally creates variable if certain keyword fail or is not present (its join two sub-domains in one keyword). 

Therefore my final question is, if this special domain(s) of keywords will be possible to customise by user or will be hardcoded?

**Comment by michalanglart** [comment]
Yes, there are more of them in `BuiltIn` library - even `Log Many` or `Comment` is one of those. Internally they call those keywords `run keyword variants` (see this: https://github.com/robotframework/robotframework/issues/2190) and they have unofficial API for such keywords as described in the issue from link.

In next version those special keywords are hardcoded in a table plus there may be some logic implemented around them. This is done this way as a minimal version because so far we had only complaints about `BuiltIn` keywords - no one came here with his own `run-keyword-variant` problems. 

However it seem to be quite hard to make it customizable for users because those keywords  are basically free to interpret provided arguments and sometimes there may be non trivial logic implemented there. Like for example with `Run Keyword If` which builds `if-else if-else` structures with nested executables, so it would be probably close to impossible (??) for users to specify somewhere in GUI where are nested executables hidden in those arguments.

So far I think that the plausible option to make it customizable would be to prepare API in RED via extension point where other plugins would be able to add logic for custom `run-keyword-variants`.  This has the obvious drawback as user would need to implement simple plugin or ask someone else to do it.

As of now however there is no topic of making it customizable - we're implementing those mechanisms only for BuiltIn keywords and will see if this would require more attention in future.


As a side note about upcoming changes in 0.8.6: there are 35 `run-keyword-variant` keywords in `BuiltIn` library. All of them will have their arguments validated differently (basically only number of arguments will be checked) so that it will resolve #96 and other similar issues raised internally. Additionally we distinguished 3 groups (or as you called them - domains) of keywords:

- keywords which creates variables out of their arguments (`Set Test/Suite/Global Variable`) - this was supported already for quite a long time, so that validation was able to detect that those variables are known in following executables
- keywords which skips variables existence check for some/all arguments - this was supported for `Set * Variable` keywords as well as `Get Variable Value` and `Comment`. Now additionally `Variable Should Exist` and `Variable Should Not Exist` will not check for variable existence in first argument.
- keywords for which validation performs some variable syntax checks on some arguments - this was already supported for `Set * Variable` and `Get Variable Value`. Now also `Variable Should Exist` and `Variable Should Not Exist` will have simple check on syntax of first argument

Additionally there is a domain of keywords which contains nested executables - basically all keywords which runs other keywords. I'm now working on some implementation which is able to resolve #28 however it seem that it will not hit 0.8.6 since it still requires some changes and testing but we're about to release 0.8.6 this week. Probably it could also solve coloring problems like in #221 but it would require more testing since coloring is performance-sensitive area.

**Comment by adam-wypych** [comment]
> However it seem to be quite hard to make it customizable for users because those keywords are basically free to interpret provided arguments and sometimes there may be non trivial logic implemented there. 

To be honest I was thinking that you do not need to treat whole line of execution as one. If you will use old technic divide and conquer, you can achieve customise ability. In my opinion if you will just check each keyword separately is not to hard to achieve possibility to have some kind of the table, which will say that argument on position 2 of keyword `X` is keyword name and start for this could be his arguments. Anyway I think the most critical for hardcoded and customizable is to decide if `ELSE` is part of keyword put as argument or is part of `Run Keyword If` syntax. This I think require to take a look how Robot Framework is parsing such syntax.

**Comment by MichaelFriis-Github** [comment]
Thank you all for the feedback.
My solution will be to create this functionality in a keyword from my referenced libraries. Which will take the validation out of the hand of RED. This way i keep the exact functionality, without making temporary fixes. 
I wont close this issue, as i think the ongoing discussion is very relevant to the community.

**Comment by adam-wypych** [comment]
@MichaelFriis-Github in my opinion you can close this issue since in GitHub exist issues, which is mostly related to the problem, which you are facing now (#28, #96, #221 and #68), but I leave decision to RED team.

**Comment by MichaelFriis-Github** [comment]
Just to show my solution - 
I used my own referenced library, 

cmd_arg_pss_ip = "${cmd_arg_pss_ip}"

status = BuiltIn().run_keyword_and_ignore_error("variable_should_exist", cmd_arg_pss_ip)
    if status[0] is 'PASS':
        settings.args['ip_address'] = BuiltIn().get_variable_value(cmd_arg_pss_ip)
    else:
        settings.args["ip_address"] = ip_addr

This way can be used, until RED supports
