### ISSUE TITLE
Provide QuickFix of suggestion for cases when Keywords are not found if the resource with this Keywords is outside the project.

### ISSUE THREAD

**Issue by gitCWS** [nokia/RED#237]
I'm importing a resource that's inside the workspace but outside the project. If I want to use the keywords from the resource then they will not be found. I can run the test suite anyway, even though the keywords are not found. 
But i can't open the Documentation or can jump to the definition of the Keyword.

Is there any solution to find the keywords, to view the documentation and all keywords from the resource?

**Comment by KrzysztofJozefowicz** [comment]
Hi
I made a simple workspace (in attachment) with 2 projects - **main** with TestSuite and, **other** with my_resource.robot resource file which contains my_resource_kw.
In **main** project, in testsuite, resource is imported from **other** project, my_resource_kw keyword is found, I can jump to KW definition in other project.

[RED-workspace_github.zip](https://github.com/nokia/RED/files/2269320/RED-workspace_github.zip)

This funcitonality has not been changed since long time, therefore I suspect you may have different case than it seems to be.
Is both projects placed in workspace or are at least on of them were imported to Workspace but phisically are not under Workspace path (to verify this,right click on Project and go to Properties->Resources to see Location path) ?

**Comment by KrzysztofJozefowicz** [comment]
Good that you found the issue. 
There should be a warning on Resource import which point that files is outside Workspace which may give suggestion what is wrong. Although as you pointed, if in Workspace, apart from Project folders you have a normal folder (in this case it will not be visible in ProjectExplorer) and tries to import resource from it from Project, you would get the same error message as trying importing from outside of workspace.

I will propose to change that warning msg to give user suggestion how to fix the situation.

**Comment by KrzysztofJozefowicz** [comment]
possible suggestions:
- you can use Import -> Import File System (right click on Project in Project Explorer) with Advanced option "create linked folder" so instead of changing you folder structure or changing resource folder to project, you can just make it visible in Project. This will allow to have KW recognized without changing paths for resource imports.
![image 3](https://user-images.githubusercontent.com/3999733/43827038-21f1352a-9af9-11e8-87b7-5f764ca4756b.png)

**Comment by michalanglart** [comment]
Closing - the changes described by @KrzysztofJozefowicz were released with RED 0.8.8
