### ISSUE TITLE
Add support for reStructuredText format in RED

### ISSUE THREAD

**Issue by danielbacara** [nokia/RED#249]
Robot Framework is able to understand *.rst files and execute the robot tables (Settings, Keywords, Variables, Test Cases) defined in there.

It would be very useful to use RED for the test suites written in *.rst files as well. 

[RF reStructuredText usage](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#restructuredtext-format)

**Comment by michalanglart** [comment]
I think this is the very first time when someone is asking to support `reST` format so it won't have high priority as of now.

**Comment by danielbacara** [comment]
Hi all,
Thank you for your comments.
When using code-blocks in an *.rst file, RF exports the robot code into a in memory *.robot file and execute it.
If the generated robot file can be accessed, then it would look like a *.robot file was used as input.

**Comment by michalanglart** [comment]
Well yes that true (a half actually because Robot handles rst files without code-blocks but with tables which looks differently).

There is however a fundamental difference between what Robot and what RED is doing with the files. The nature of interpreter/executor is different than the nature of editor with all its features. For example Robot don't have to know that for example the keyword `My Keyword` is defined in file `file.robot` starting from character `1729` and ending `200` characters from there. This is on the other hand very important knowledge for editor.

For RF the files are read-only but the editor has to make them editable and be able to save those files properly. That's why RF can only cut `plain-text` pieces from code blocks and totally ignore the rest of the file pretending that this is a `.robot` file. Editor on the other hand has to properly handle the ignored parts (at least be aware of that parts so that they are not removed when file is saved).

Yes - probably lots of existing code from our parser can be reused to support `.rst` format but it's not that simple as it looks at first sight and it will of course consume much more time than it seems.

**Comment by michalanglart** [comment]
Closing. No plans to provide integration with rst suite format
