### ISSUE TITLE
Execution order based on directory name is ignored in argument file 

### ISSUE THREAD

**Issue by ahojuk** [nokia/RED#253]
I have two separate test suite folders named as 001_Suite and 002_Suite.
If I right click one of them and select Run As => 1 Robot Test
RED will run both of them instead of just one that I selected.

In argument file I see:
'# arguments automatically generated
--suite      Project.Tests.Suite

I expect argument file to be something like this:
'# arguments automatically generated
--suite      Project.Tests.001__Suite

Picture of my test suite:
![image](https://user-images.githubusercontent.com/7523736/47297945-3701df80-d61f-11e8-96f2-af1e53226d38.png)

**Comment by modrz** [comment]
Hi,

As pointed in documentation Robot Framework removes order prefix when suite names are created (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation).

If order prefix is left as you suggested, Robot will raise following error:
[ ERROR ] Suite 'Project' contains no tests in suite 'Project.Tests.001__Suite'.

In you case suites should be named like 001_Suite_1 and 002_Suite_2 when you want to run them separately.

**Comment by ahojuk** [comment]
In Terminal I can run just one Suite like this:
robot 001__Suite
I expect same behavior in RED UI.

Different suites are maintained by different testers.
If prefix is only thing differentiating suite names then it is easier to combine them later to single test result using rebot.
That's why I prefer to use same Suite names.

Other fix to this issue would be to let users edit the default argument file.
Now I don't see option to replace default "--suite      Sotevv-testit-raptor.Tests.Suite" line.

# arguments automatically generated
--suite      Sotevv-testit-raptor.Tests.Suite

**Comment by michalanglart** [comment]
By default RED is launching tests by issuing (simplified command line):
```
robot --suite Project.Suite path/to/your/project
```

so your project is always the `data_source` and selector is added to choose proper suite inside the project. In your example you're doing:

```
robot path/to/your/project/001__Suite
```

Without selector.

The good news is that there is a preference: `Robot Framework -> Launching -> Run single suite using suite path`. This does precisely what we would like to have (passing selected suite as data source instead of a project with selector) but the bad news is that currently this only works when suite files are selected, not directories. We will remove this restriction in next release as it does not seem to be needed for anything.

**Comment by ahojuk** [comment]
Sounds great to me! I wait for the next release :)

**Comment by michalanglart** [comment]
No more waiting: 0.8.9 is there and one can run directories together with above-mentioned preference turned on

**Comment by ahojuk** [comment]
Tested and this works perfectly now. Thank You!
