### ISSUE TITLE
The PyDev debug documentation is too vague

### ISSUE THREAD

**Issue by joeyjoeyjoeyjoey** [nokia/RED#255]
I cannot understand the following documentation.   It is too vague.  
http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html

I have know idea what I need to do with runPyDevDebug.py
In the "Debug configuration setup" section 
I cannot specify the interpreter in the Executable file section.  It only accepts py files
I cannot add runPyDevDebug.py path to the Additional executable file arguments it requires a variable name and I do not know what that is.

**Comment by modrz** [comment]
Hi,

If you have pydevd module installed in your interpreter you do not need to do anything in runPyDevDebug.py. Just create debug configuration with paths to interpreter and runPyDevDebug.py file, like in following screenshot:

![image](https://user-images.githubusercontent.com/22540835/47781148-49ee7100-dcfd-11e8-8faf-3b3c31fc4fc9.png)


You can also install only PyDev for Eclipse and modify runPyDevDebug.py by specifying correct paths like:
`
    pydevd_path = 'C:/NOKIA/RED/RELEASES/0.8.8/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc/pydevd.py'
    robot_run_path = 'C:/Python27/Lib/site-packages/robot/run.py'
`

**Comment by joeyjoeyjoeyjoey** [comment]
Thank-you for the quick response 

I added the paths as described; started the debug server; placed a break-point in the Robot test

But I still get the PyDev needed message when I try Step Into (F5) the library method:

> The keyword LoginLibrary.Create  … external library. … not able to debug both Robot and python code however it is possible to setup cooperation with other debugger …

The Step Into (F5) does not work; however, a workaround is to click on the “Click here” to open the source.  

> Click here to try opening source of this keyword.

Then add the break-point to the library method.  Then Step-Over(F6) and the debugger will stop at the break-point in the library.  

Thanks for the help

**Comment by michalanglart** [comment]
Hi,

The way you've described it above is presicely the way it works as of now. 

To understand it you have to keep it mind that RED implements debugger capabilities for Robot code only. So e.g. step into python code does not work because it does not "see" underlying python code. 

There is only possibilty to combine RED debugging session together with pyDev debugging session in a manner described above or in user guide.

**Comment by stonerzju** [comment]
Hi - 
Thanks for your information, I was finally able to debug user library with your help. But I am only able to do it on Linux, on my windows, I am not able to add the break point for user libraries. When i double click on the left of my source code, it pop up a window to set the Bookmark. 
I have followed the sequence to set the project to PyDev project. And have the run configuration setup correctly.
Does anyone can give help on this?

**Comment by qianchangchun** [comment]
I also can not understand how to debug the python code， I really did according you described but I can still can not debug python code， so it make no sense to do so much configuration,  and I find that you assigned this task to michalanglart, and he add this to the 0.8.12,  is that mean the debug feature have problems

**Comment by qianchangchun** [comment]
Actually I found that if I set breakpoint in the python library,  I can debug but I can not debug into the python when I set the breakpoint in the robot source codes.

**Comment by michalanglart** [comment]
No, the debug feature does not have problems. However @joeyjoeyjoeyjoey is right that the description of setup of RED-PyDev sessions is too vague so we've decided to simplify it. Next version will have a wizard which will be able to create launch configuration to be used in such session.

> Actually I found that if I set breakpoint in the python library, I can debug but I can not debug into the python when I set the breakpoint in the robot source codes.

What do you mean by that? As I already stated 3 comments above RED is able to debug Robot code and PyDev is able to separately debug python code. It is possible to combine those two and get two co-operating debugging sessions. However you cannot for example directly "Go Into" the python code with F5 when debugging Robot code.

**Comment by qianchangchun** [comment]
My mean was that if I set a breakpoint in the python library code, then I debug the robot souce code, the eclipse can bring me to the breakpoint where I just set in the python library code,  and if I set a breakpoint in the robot source code,  as you described above, I can not go into the python code directly.  Now I seems understand, I have to find the corresponding python library and then continue the debugging. And there is another problem that after entering the python library code debugging, I can not easily jump out from the python library  debugging, I would enter the robot library itself to keep on debugging, but that was not what I wanted. The only quick way to jump out from the library debugging is to resume to the robot source code.

**Comment by michalanglart** [comment]
The user guide: http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html was udpated and now it guides through the wizard which allows creating launch configurations. There are also no manual steps now (previously some changes in script had to be made)

**Comment by manosnoam** [comment]
Thank you, it works well with the new red-pydevd package.
I've submitted a new issue, while getting permission denied if installing red-pydevd with eclipse UI: #305

**Comment by humbienri** [comment]
Which version of RED are you referring to?  I've been at this for hours now trying to set up on Windows to get RED and PyDev to play well together so that I can debug both the *.robot files AND some of the Keywords that I have written in Python?

I can't seem to find (for download) some of the python modules, like redpydev.py?

runPyDevDebug.py can also be downloaded from where?

Please help.  This would be a boon to my productivity.
Thank you!

**Comment by humbienri** [comment]
Progress!  I've managed to get this to work somewhat.  I can now hit/snag onto the breakpoint in my Python file which is great since that is what I now need to troubleshoot!  Thank you all!  This was not easy.

**Comment by michalanglart** [comment]
Hi,

can you tell us what exactly is hard still? There is a wizard with 3 steps and it is explained in more details in user guide. With which step did you had problems?

**Comment by humbienri** [comment]
I think my issue is figuring out how to update either RED or the PyDev plugin or just figuring out what versions of what I had.  I think the English is also a bit of problem.

So trying to find the runPyDevDebug.py file was a problem and yet now it seems it is not relevant at all.  Perhaps that this issue (255) contains both the "new" way of doing it and the "old" way of doing it also adds to the confusion.  The instructions in Eclipse Help also seem to be outdated but that may be because I had an older version of RED perhaps?

I'm trying to remember what I ended up having to update. Both PyDev AND RED I think.

It was confusing to say, redpydevd.py comes WITH RED.  Yet I had RED installed but no redpydevd.py file.

Ultimately I ended up returning to the very beginning AFTER having done the updates and launching the Wizard for Debug Configurations and only then did it work as you described.  I think that is why I had asked the question, "what version".

There's room for improvement in the instructions I think but it might be a language issue?

Thank you all though!

**Comment by michalanglart** [comment]
Yes, this issue contains some instructions regarding both the old and the new way since the latter was introduced as a "fix" for it. For example `redPyDevDebug.py` is old way. This script was renamed (not only, there were changes inside it too) to `redpydevd.py` to make it more similar/symmetric to `pydevd` module provided by PyDev which is also required. 

Regarding user guide: the one which you can read through in your eclipse/RED help system is provided with RED so it describes the version you have. The one which is available online at nokia.github.io/RED/help is always generated from latest version.
