### ISSUE TITLE
Possibility to define default Environment variables for launch configurations

### ISSUE THREAD

**Issue by p74** [nokia/RED#273]
I try to enable the rf sys logging in eclipse, but i can not find a way how to do this.
i use now the command line:

export ROBOT_SYSLOG_FILE=/tmp/syslog.txt
export ROBOT_SYSLOG_LEVEL=DEBUG
and then start eclipse in the command line

is it possible to enable this in the project or in my red settings?

thx

**Comment by michalanglart** [comment]
Hi,

I've just checked under windows and following scenarios works for me:

1) Pretty much your scenario under Windows 10 using Git bash:
`export ROBOT_SYSLOG_FILE=/d/tmp/syslog.txt`
`export ROBOT_SYSLOG_LEVEL=DEBUG`
`./RED.exe`

You can verify if those environenment variables are visible in RED/eclipse by going to: Help -> About RED (or About Eclipse) -> Installation Details -> Configuration. At the last tab there should be a section `*** System environment variables`. Check if those two are defined there. If yes then those variables are also propagated to robot tests launched from RED. In my case the file is properly created and filled with data.

2) This is a bit less convenient: you can define environment variables for each launch configuration (http://nokia.github.io/RED/help/user_guide/launching/local_launch.html) on `Environment` tab as visible in my example below (the PYTHONIOENCODING is a variable we always append when launching tests):

![env_vars](https://user-images.githubusercontent.com/14932410/52774988-e33c5b80-303e-11e9-9485-383947db7a3d.png)

This works for me too. This is however less convenient because as of now you cannot define default environment variables to be added for each newly created launch configuration. You can only change it in particular configuration.

**Comment by p74** [comment]
Ok thx for the feedback, it would be nice if this is added in the further
(but i understand also that this has low low low prio),

i will keep use option 1.

Op do 14 feb. 2019 om 09:58 schreef michalanglart <notifications@github.com

**Comment by michalanglart** [comment]
I've changed the title to reflect the actual task to be done

**Comment by michalanglart** [comment]
Provided in 0.8.12. Please have a look to Preferences -> Robot Framework -> Launching -> Default Launch Configurations. Each **newly** created launch configuration will have those env variables preset
