### ISSUE TITLE
How to pass variable defined in red.xml to tests execution

### ISSUE THREAD

**Issue by tyat92** [nokia/RED#276]
Hello,

I saw in the changelog of the 0.8.11 version that "Variable files defined in red.xml are not passed to tests execution".

I can manage to pass a given file path in the run configuration using the Additional Robot Framework arguments, but is there another way to do it for the whole project ?
Is there an environment variable that corresponds to the files listed in the red.xml ?

By the way, it could be interesting to have an option in order to only use variables files in red.xml for validation (as in 0.8.11 version), or for validation and test running (as in 0.8.10 version for example).

Thank you for your work !

**Comment by michalanglart** [comment]
> I can manage to pass a given file path in the run configuration using the Additional Robot Framework arguments, but is there another way to do it for the whole project ?

In preferences you can specify `Additional Robot Framework arguments` as default - each newly created launch configuration will have it filled too. This is a little bit different than the file defined in red.xml because in preferences this is global while in red.xml this is a per-project setting. We do think that this is marginal because most of users have a single project so global setting is equivalent to project setting.

I'll give you some background and longer justification on why we decided to change the behavior. For our internal clients in Nokia it is a common setup that they launch tests for different "environments" and the "environment" is somehow determined by variable files they provide when launching. Due to this requirement we provided for them possibility to use eclipse string-substitution variables in launch configuration (this was also requested from external users - see #184). With this feature they could specify variable files in `Additional RF arguments` field also using eclipse-variables so as a result they could change the value of the eclipse-variables and run tests again against different environment. Then in 0.8.11 we went a step farther and provided a feature which allows to quickly switch between different sets of eclipse-variables values (see http://nokia.github.io/RED/help/user_guide/launching/string_substitution.html).

We found ourselves in a situation where:

1. it is possible to define variable files in red.xml
2. it is possible to define `Additional RF arguments` where also variable files can be passed for launches

Now (1) was used in two use cases:

1. to attach those files when launching tests
2. to provide dummy variables file so that validation will not complain about missing variables which useful when variables are created dynamically when tests are running

The use case 1.2 is also covered by filling `Additional RF arguments` in preferences (modulo global vs project setting case).

On the other hand it created a problem for those users who were using both ways: provided dummy files to silence the validation as well as adding variables files through launch configurations in order to parameterize them and use our "environment quick-switch feature". The problem was that their tests didn't worked when started from RED since the command line looked like this:

`... --variablefile some_important_env_var_file.py --variablefile dummy_file_to_silence_validation.py ...`

where the variables files from red.xml were coming after those from `Additional RF arguments` which caused actual variables to be overridden with some dummy values (the value is taken from last file). Of course we could switch the order but this can be also unreliable since there are some dummy variables leaking into the launch which can again lead to different problems (different results when launched from RED than when launched in some CI service).

> By the way, it could be interesting to have an option in order to only use variables files in red.xml for validation (as in 0.8.11 version), or for validation and test running (as in 0.8.10 version for example).

Yes we were considering such option however:
- as I've said we believe that "attach variable file" use case is covered in different place
- adding even a checkbox always complicates the overall product/tool (yeah just slightly but stiill)
- removing attaching variables file from red.xml gives opens up possibility to simplify RED (in next points)
- since variables files in red.xml are only used to provide variable names for validation (so that it will not complain) then those files can be very simple so no arguments for var files are needed - thus we can remove all those `Argument` columns from whole table - it can be simply a list of files
- transforming the current table into list makes it possible to for example move `Variable mappings` part from different page to the same as they are validation-related (`Excluded project paths` is too but this probably requires another page)

So overall it seems that there is very little or no drawbacks while it simplifies whole RED in couple of aspects (no overlapping use cases + UI simplifications which are always good for the user and the learning curve).

If you really feel that we should provide a checkbox which would allow attaching variable files from red.xml to launches then please provide us with some good reasons for that because we've already started some work on farther simplifications in red.xml editor which I've mentioned above.

Oh and BTW - since it is possible to parameterize `Additional RF arguments` it also easily achievable to provide different variable files for different projects even if someone uses multiple projects in his/hers workspace.

**Comment by tyat92** [comment]
Hello,

Thank you for the enlightenments. Indeed, I did not known the dummy variable use case and I know understand why you have decided to change the behavior.

Thanks again for you work !
