### ISSUE TITLE
Add Python library file with .pyw extension

### ISSUE THREAD

**Issue by TRBTA** [nokia/RED#283]
Hello,

I have a file with the .pyw extension and want to add it in the red.xml as a Python library. 
The problem is i can't add the .pyw file. If I change the file extension filter to `*.*` 
![extensionselection](https://user-images.githubusercontent.com/48476431/54195038-f87d9c00-44bd-11e9-9b45-b1a9948ecd5c.jpg)
and try to add the .pyw file RED throws an exception.
![exception](https://user-images.githubusercontent.com/48476431/54195069-0c290280-44be-11e9-8810-57d3c7d9f6cb.jpg)
My current workaround is to rename the .pyw file to .py in the windows explorer, add the .py file as Python library and rename it again to .pyw. 
After the workaround i can use the keyword in the .pyw file with my testcases. 
If I keep the file as .py the script won't work and with .pyw it works so i need it to be a .pyw file. 

I'm currently using the RED program version 0.8.11 on Windows with Python 3.6.8 32bit version. 

Is it planned to add the compatibility for .pyw files or is there a way to already do it? 
Thank you for your answer!

**Comment by michalanglart** [comment]
Hi,

> Is it planned to add the compatibility for .pyw files or is there a way to already do it?

Not really, but it looks doable.

However out of curiosity: I have very little experience with GUI-based application in python. From what I understand `pyw` extension exists for Windows in order to associate this type of file with `pythonw.exe` instead of `python.exe` which are GUI-based (the first) and CLI-based (the latter) interpreters. This is done in order to make such file "double-clickable". I've also found opinions that basically the entry point to GUI-based application should be `pyw` file while all the others should be `py` files. If that's true then the question is: should the entry-point file to application be also a keywords library for RF?

**Comment by TRBTA** [comment]
Hello,

thanks for the reply. 
Your assumption is right. It may be better style to call the pyw file from another py file to have the entry-point file split from the keywords library for RF. 
In the end I won't need the added compatibility for pyw file in the "add python library" selection because the call of the .pyw file from a .py file works fine.
Thank you for the correction!
