### ISSUE TITLE
Equivalent to "Immediate" window

### ISSUE THREAD

**Issue by humbienri** [nokia/RED#289]
Hello,

I apologize as this may not be the best place to ask this.  Thank you for RED, am using it on a daily basis and want to become a more advanced user but I've not been able to figure out how to invoke the equivalent of the Immediate window like in Visual Studio.  It's been a while since I use it so I may have it wrong.

Basically looking for the ability to set a Breakpoint and Debug one of my test cases and when the Breakpoint is snagged, then open up some Window/Perspective and be able to type in commands there.  For example to inspect a Variable, specifically a "dynamic" variable that is using Robot Framework's Extended Variable Syntax?

Thank you all.  Keep up the excellent work!

**Comment by michalanglart** [comment]
Hi,

there is no better place to ask for new features than the issue tracker :)

It's been a while since I used Visual Studio last time but from what I found in documentation the _Immediate window_ is a place where you can type in expressions end evaluate them. In Eclipse world there is at least 1 place for that:

- generic _Expressions_ view (here for JDT: https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fviews%2Fdisplay%2Fref-debug_shell_view.htm)

Additionally different plugins provide own means for achieving similar functionality. For example JDT (Java Development Tools) gives us:

- _Debug Shell_ view (https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fviews%2Fdisplay%2Fref-debug_shell_view.htm)
- _inspection_ mechanism on code selected inside editor


In case of RED we were talking once or twice about something similar but so far no user (whether Nokia-internal or external) asked about such functionality.

From my point of view this could be something like _Debug Shell_ view in which it would be possible to:
1. evaluate variables-like expressions e.g. type something like `${dictionary[key]}` in order to get the result
2. evaluate keywords with arguments provided: `Convert To Lowercase    UPPER`
3. evaluate python code (technically this could be equivalent of calling `BuiltIn.Evaluate` keyword)

Actually RED already has some internal mechanisms implemented which could be reused for keywords evaluation while debugging because we have _conditional breakpoints_ (http://nokia.github.io/RED/help/user_guide/launching/debug/breakpoints.html) where user can give keywords to pass/fail (functionality 2 from list above) and decide if debugger should stop or not.

I like this feature and it looks like it could be implemented rather easily but nevertheless we would need some time for that.

**Comment by humbienri** [comment]
Your reply reminded me that I looked into this a few months ago but never got it to work correctly.  Presently, there is an Expressions View that I can get to display in RED.  However, when I enter a dynamic expressions like ${SOLUTION_SWITCHER_GENERIC_PRODUCT_LOCATOR.replace('PRODUCT_NAME_PLACEHOLDER' , 'Accounting' , 1)}  for the Name of the Expression, the Value column of the Expressions View just reports <error(s) during_the_evaluation>

It shows an error even for a "non-dynamic" Expression/Variable.  I'm guessing the Expression View is more like the Variables View?

Thank you for your insights! I really am surprised nobody else has asked for something like this.

Kind Regards,

**Comment by humbienri** [comment]
Ah, I think I now understand your reply. The Expressions View is not specific, or relevant, to Python and/or Robot Framework?

**Comment by michalanglart** [comment]
Yes, I meant that Expressions view is a generic view provided by platform. RED however does not implement any APIs needed to be able to evaluate those expressions in Robot Framework context.

**Comment by michalanglart** [comment]
Hi, we are finishing implementing small view which would (hopefully) serve your needs. Here is a under-dev RED 0.9.2 which you can install and play with it.
[RED_feature_0.9.2.201911251107.zip](https://github.com/nokia/RED/files/3886597/RED_feature_0.9.2.201911251107.zip)

If you have some time for it - could you check it and give us some feedback if it is something you were thinking of?

**Installation**

Simply open _Help -> Install New Software_, then click _Add..._ button and _Archive..._. Select downloaded zip file and proceed with the installation normally.

**Usage**

We've created a separate view (open with _Window -> Show View -> Other_, then select **Debug Shell** view; alternatively can be opened from source editor with context menu action **Inspect call/Inspect variable**).

The view resembles a shell in which one can write expressions in 3 different modes:
- **ROBOT** where you can write keyword calls like `Should Be Equal    ${x}    5`; under the hood it goes through **BuiltIn.Run Keyword** keyword
- **VARIABLE** where you can get the values of variable-like expressions
- **PYTHON** where python expressions are evaluated; under the hood it is called via **BuiltIn.Evaluate** keyword

Any feedback is apprieciated so that 0.9.2 would have this feature working as expected. As of now we have fixed all the issues we've found and we do not plan to change anything. We only have doubts if the **PYTHON** mode should use the `eval()` or `exec()` (currently eval under Evaluate keyword) - in latter case it would be possible to write python statements like `x = 5 + 10` not only expressions like `[x for x in range(7)]`. Which one do you think should be used in python mode?

**Comment by humbienri** [comment]
Greetings @michalanglart, it's been a minute!  Looks like you fine folks have been quite busy though.  I'll dowloand your latest update and give this Immediate thing a try; over the holidays here.

You folks are awesome! So, thank you for all this.

**Comment by humbienri** [comment]
Apologies, I thought I'd responded already.  Guess I just thought about what to say, rather than actually say it.

To your point of `eval()` vs. `exec()` I would recommend staying with `eval()` even though from what I've read, `exec()` seems more powerful yet more "cryptic".

In the past, from what I remember (years ago) I would use the "Immediate" panel to "probe" the system to get some value or state out of it.  Not to actually drive it or make it do/go.

From what I can tell, if engaged in `exec()` mode, the reply/response will be `None` which I think would be confusing to most (not all, but majority) of users.  I envision that most users of RED will not be hard code programmers let alone hardcore python programmers so usage of `eval()` would be easier to comprehend for them.

One defect that I've found, not major IMHO, is that as a shell and traversing through the command history (using the Up arrow to retrieve previously run commands) works okay for automatically switching the command but it doesn't also automatically switch the mode.  So one then gets the scenario, for example, of having a "python command" in a "Robot mode".  Not a big deal but something to note.

**Comment by michalanglart** [comment]
> exec() seems more powerful yet more "cryptic".

That's my worry too - it would require more knowlodge about the context in which those statements passed to `exec()` are executed. Plus I'm not sure if it's really useful to be able to define a simple class for example or a function.

Nevertheless if someone would come up with a good use case for having `exec()` then nothing is closed - we can add another mode after all :)

Regarding the defect you've found: now I don't remember if anything have changed in the implementation after I've attached the zip here but in general it should work. On the gif below I'm "executing" 3 expressions in different mode and then tracers through history and the mode is changed:

![modes](https://user-images.githubusercontent.com/14932410/70263789-6fb73680-1797-11ea-98d8-4bf8599f870e.gif)

If you're able to reproduce it please show us, maybe there is some bug (or indeed it changed after I've build the attached zip although I'm pretty sure this is the version which was not touched since then)

**Comment by michalanglart** [comment]
Hmm, now when I'm looking at the gif - the mode is changed indeed, but the buttons states is not updated

**Comment by humbienri** [comment]
Yes, you are right.  I remember seeing that behavior where the mode (upper right) did not change.  But I didn't explain it correctly, or I'd forgotten. Sorry about that.

As to the command history not also toggling the mode, within the actual shell, disregard that comment.  I am not able to reproduce it so I think I might have confused myself.

Yes, I'd say, start simple on the `eval()` vs. `exec()` dilemma.  Let the "need" for `exec()` come up from the users themselves.  I myself am no power user of Python, so I'd never heard of this.  Best to not overengineer things.

I'd actually not used RED for a few months now as I'd been tasked with other non RobotFramework work but made it a point to come back and fix some broken tests just so I could get my hands on this Debug Shell feature you'd implemented.  I am looking forward to leveraging it more!

Thank you Michal!

**Comment by humbienri** [comment]
I am curious @michalanglart , what software tool do you use to create your animated GIFs?  I prefer them over video but making them is rather manually labor intensive and thus time consuming.

**Comment by michalanglart** [comment]
It's called ScreenToGif: https://www.screentogif.com/ and I would absolutely recommend it. Really easy to use it altough it's Windows only.

**Comment by humbienri** [comment]
I'm familiar with it.  Unfortunately, that is the one I found to be rather time consuming in editing the resultant frames to remove duplicates that don't really add much value.

Thanks again Michal.

**Comment by michalanglart** [comment]
Well, we probably have different needs. I don't use the editor at all - I just need to record couple-of-seconds scenarios to demonstrate how something works or how something is broken and it serves this purpose very well.

**Comment by michalanglart** [comment]
The view is provided in RED 0.9.2
