### ISSUE TITLE
Is 32bit RED editor package for windows available?

### ISSUE THREAD

**Issue by sharadw1986** [nokia/RED#292]
In repository of RED editor I can not see 32 bit package for RED editor? Is there is any 32bit package available for Windows? If not, is there is plan for 32 bit release?

**Comment by modrz** [comment]
Hi,
We only release 64 bit packages.
You can download 32 bit version of Eclipse and install RED feature.
Check following issue for details #267

**Comment by michalanglart** [comment]
As to the future: no, there is no plan to release 32 bits version. Moreover I'm not sure if this would be even possible to prepare such package once we switch to newer eclipse platform. Currently RED is being build on Eclipse Oxygen released 06.2018. There are 3 newer Eclipse releases called: 2018-09, 2018-12 and 2019-03 of which only the first one is officially supporting 32 bits. As of now I don't know however if eclipse just stopped building 32 bits packages but it is possible or if they dropped it permanently so that it is not even possible to prepare such package.
