### ISSUE TITLE
Why there is no menu “Robot framework” when right click the robot project

### ISSUE THREAD

**Issue by qianchangchun** [nokia/RED#299]
I‘m using RED by install the plugin in the market place， and in the past I find that when I right click the robot project, there is a menu called "Robot framework", but this morning I found this menu disappeared. I download the RED windows zip and run the RED.exe,  this menu would exist. I don't know why this menu did not show when I using the official eclipse with the RED plugin. By the way, my eclipse is Photon. Could somebody help me? Thanks

**Comment by michalanglart** [comment]
Hi,

this menu has no restrictions on it's visibility (so it should be always visible regardless what is selected or which perspective is active etc.). However it is defined for `Project Explorer` view. Are you sure that you tried to open it in this view? Depending on your eclipse installation you may have some different views which are very similar to `Project Explorer`. For example Eclipse for Java programmers installation have Java perspective open by default in which `Package Explorer` view is the default one.

**Comment by qianchangchun** [comment]
I'm sure I choose the correct view.
![image](https://user-images.githubusercontent.com/26403275/57424544-9edde780-724a-11e9-815d-327340001683.png)

**Comment by michalanglart** [comment]
On your screenshot you can clearly see that the view is `PyDev Package Explorer` not `Project Explorer` and as I said the `Robot Framework` menu is defined for the latter. Please use `Window -> Show View -> Other -> General -> Project Explorer`.

In general there is a mess in eclipse when it comes to views displaying your workspace/projects. First of all the raw eclipse platform has 2 views serving similar purposes:
- `Navigator` view
- `Project Explorer` - which is language agnostic and higly customizable; it should be prefered over `Navigator`

However any feature you will install in eclipse is free to provide own views and sadly some of them provide another views serving similar purposes. For example:
- `PyDev` (Python support) provides `PyDev Package Explorer`
- `JDT` (Java Development Tools - Java support) provides `Package Explorer`

As a result someone who have Eclipse+PyDev+JDT (myself for example) can choose between 4 different views all serving a bit similar purpose instead of using generic one (`Project Explorer`). RED thankfully does not extend this mess by not providing own `Robot Project Explorer` view but it is using generic `Project Explorer` instead.

**Comment by qianchangchun** [comment]
Thanks very much， it is really very strange for a new guy of the eclipse， I really never noticed the difference of the PyDev Package Explorer and the Project Explorer. Now I have find it and adjust it to the right position

**Comment by michalanglart** [comment]
I'm not that new to eclipse and still find it weird that there are so many views serving similar purposes provided by different add-ons.

For at least couple of years I'm using `Project Explorer` in my daily work and it serves my purposes well - whether I'm working with Java or with Python I don't need those explorers provided by `JDT` or `PyDev`.
