### ISSUE TITLE
Where can I find runPyDevDebug.py?

### ISSUE THREAD

**Issue by humbienri** [nokia/RED#310]
Hello folks,

I have downgraded from RED v. 0.8.12 to v. 0,8,11 and am trying to get PyDev debugging set up.  It was a suggestion by @michalanglart since I was having too many problems on v0.8.12.

But I now remember why I had originally upgraded to v0.8.12, because in the Help documentation for PyDev/Robot debugging setup, I am instructed to download file runPyDevDebug.py from https://github.com/nokia/RED/tree/master/src/RobotUserScripts but no such file exists there.

Where can I find such file?

Thanks you,
-Humberto

**Comment by michalanglart** [comment]
Hi,

this file was removed because the intagration of RED and PyDev has changed a bit in 0.8.12. Luckily this is a git repo so one can browse its history at any point in time. This file is stiil there one commit before the latest in above mentioned src/RobotUserScripts directory: https://github.com/nokia/RED/tree/d0ad0d2959a992f5d6e65475f673655c4b855029/src/RobotUserScripts
