### ISSUE TITLE
inlcude/exclude of test cases does not seem to work

### ISSUE THREAD

**Issue by StefanRas** [nokia/RED#334]
I have excluded some test cases for execution, but they are still being executed. 
![image](https://user-images.githubusercontent.com/56152270/66746055-0dba0f00-ee81-11e9-95ef-dfc8df2399d0.png)

The argument file does not have the --exclude option:
![image](https://user-images.githubusercontent.com/56152270/66746101-36da9f80-ee81-11e9-9ccb-9eb2c64a4654.png)

Eclipse 2019-06 / RED 0.8.13

**Comment by michalanglart** [comment]
> I have excluded some test cases for execution

Actually you've just excluded some parts of your project from **validation** not from **execution**. See this topic in RED user guide: http://nokia.github.io/RED/help/user_guide/validation/scope.html

RED GUI directly speaks about validation, not execution. See:

![exclude1](https://user-images.githubusercontent.com/14932410/66747113-06483500-ee84-11e9-92c2-961c66ebd913.png)
![exclude2](https://user-images.githubusercontent.com/14932410/66747115-06483500-ee84-11e9-92e5-bbccc4507517.png)

Moreover `--ecxlude` option of Robot Framework works by excluding test cases based on `[Tags]` assigned to those tests while you are trying to omit some suites/tests based on their location in project.

There are only 4 cmd line options I'm aware of which are used to filter suites/tests. Firstly `--test` and `--suite` which work by providing names of suites/tests which should be executed and this takes location into account because the names are long-names like "Suite1.Inner.Test". The other way is to use `--include`\`--exclude` options but those work on `[Tags]`.

If you only want to run your suites 01-04, then select those 4 and run them:
![run_as](https://user-images.githubusercontent.com/14932410/66747954-2d076b00-ee86-11e9-8d32-2ee403661fd6.png)

Only those 4 will be executed. If you would open launch configuration created for this (`Run` -> `Run Configurations` and find the one created there under `Robot` node) you would see something like this:
![launch_cfg](https://user-images.githubusercontent.com/14932410/66748008-545e3800-ee86-11e9-985f-d6e6ab89133f.png)

This mean that the project `ME_CAMMOD_QualificationTests` will be used as `data_source` for Robot command line and the 4 suites will be chosen by using `--suite` argument.

**Comment by StefanRas** [comment]
Hello,

This is really helpfull. It's always easy afterwards 😉

Regards,

Stefan



________________________________
Van: michalanglart <notifications@github.com>
Verzonden: maandag 14 oktober 2019 13:28
Aan: nokia/RED <RED@noreply.github.com>
CC: StefanRas <stefan_ras@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nokia/RED] inlcude/exclude of test cases does not seem to work (#334)


I have excluded some test cases for execution

Actually you've just excluded some parts of your project from validation not from execution. See this topic in RED user guide: http://nokia.github.io/RED/help/user_guide/validation/scope.html

RED GUI directly speaks about validation, not execution. See:

[exclude1]<https://user-images.githubusercontent.com/14932410/66747113-06483500-ee84-11e9-92c2-961c66ebd913.png>
[exclude2]<https://user-images.githubusercontent.com/14932410/66747115-06483500-ee84-11e9-92e5-bbccc4507517.png>

Moreover --ecxlude option of Robot Framework works by excluding test cases based on [Tags] assigned to those tests while you are trying to omit some suites/tests based on their location in project.

There are only 4 cmd line options I'm aware of which are used to filter suites/tests. Firstly --test and --suite which work by providing names of suites/tests which should be executed and this takes location into account because the names are long-names like "Suite1.Inner.Test". The other way is to use --include`--excludeoptions but those work on[Tags]`.

If you only want to run your suites 01-04, then select those 4 and run them:
[run_as]<https://user-images.githubusercontent.com/14932410/66747954-2d076b00-ee86-11e9-8d32-2ee403661fd6.png>

Only those 4 will be executed. If you would open launch configuration created for this (Run -> Run Configurations and find the one created there under Robot node) you would see something like this:
[launch_cfg]<https://user-images.githubusercontent.com/14932410/66748008-545e3800-ee86-11e9-985f-d6e6ab89133f.png>

This mean that the project ME_CAMMOD_QualificationTests will be used as data_source for Robot command line and the 4 suites will be chosen by using --suite argument.

**Comment by michalanglart** [comment]
Ok, happy to hear! I'm closing the issue then.
