### ISSUE TITLE
Variable defined in red.xml is not recognized in robot file

### ISSUE THREAD

**Issue by bstephgit** [nokia/RED#337]
Hi,
I have defined in red.xml a variable ${TM_TEST_ROOT_PATH} (variable mappings section) with a path value.

when I use it in robot file:
${TEST_LIB_PATH}=   ${TM_TEST_ROOT_PATH}/Tests/resources/libs/robot_lib/

 ${TM_TEST_ROOT_PATH} is underlined in red and not recognized.

whereas it is used at top of the file without any problem with the declaration:

Resource  ${TM_TEST_ROOT_PATH}/Tests/presets/resources_list.robot

Is this a known issue? Any workaround?

**My eclipse version is:**
Eclipse IDE for C/C++ Developers
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

**RED - Robot Editor**
Version: 0.9.0
Development environment for Robot Framework http://www.robotframework.org/
(c) Copyright 2015-2019 Nokia Solutions and Networks.

Thank you

**Comment by joanna-may** [comment]
Hi,
Variable mapping is only used in "*** Settings*** section. Those mappings will be used by RED for resolving parameterized paths in Library, Resource and Variables settings.

**Comment by bstephgit** [comment]
If I correctly understand, variables defined in variables mapping section in red file, cannot be used in robot script files as regular variable, isn't it?

**Comment by michalanglart** [comment]
You can use any variables you want in robot files. Variable mapping is a way to tell RED how to behave when it sees parameterized import so that it can provide keywords/variables defined in the imported file/library.

If you want to silence the error marker about undeclared variable usage you can define this variable in python file with some dummy value and add it to `red.xml` file in `Variable files` section under `Variables` tab.

**Comment by bstephgit** [comment]
ok thank you
