### ISSUE TITLE
Unable to fetch values from red.xml variables

### ISSUE THREAD

**Issue by deepaleekhare31** [nokia/RED#352]
In my red.xml I have declared a variable ${path}.
When I try fetching the same in my test suite settings section.
Variables ${path}/Generic_Configurations/Generic_Config.py
or
Resource ${path}/Resource_Files/Keywords.robot

![image](https://user-images.githubusercontent.com/50138350/69553111-97ebac00-0fc5-11ea-84ed-991e04862c6e.png)

It does not show any error from the eclipse editor, even if I do Ctrl+Click, it traverses to the respective file.
But while execution of a testcase I'm getting below error:
Replacing variables from setting 'Variables' failed: Variable '${path}' not found.

Could u please tell me, why the path value is not being fetched from red.xml?

**Comment by deepaleekhare31** [comment]
@modrz Could you please help ?

**Comment by michalanglart** [comment]
Hi,

first of all - on your screenshot you have variable `${pat}` not `${path}`.

Secondly: the behavior you've described matches the description in the table:

> Define variable names and values. Those mappings will be used by RED for resolving parameterized paths in Library, Resource and Variables settings.

As it is stated RED is using those values in order to know where is the imported file. Without it we wouldn't know what file are you importing because the value of parameter is known in runtime just before the import is done. RED on the other hand needs to have this knowledge statically without executing anything hence it uses Variables Mapping for that. **However**: this does not mean that those values will be injected into execution - you have to do it using other means - for example by providing `--variable` arguments to default launch configuration in Preferences.

**Comment by deepaleekhare31** [comment]
Thank you @michalanglart 
But, Let's take an example here: http://nokia.github.io/RED/help/user_guide/working_with_RED/variable_mapping.html
They have created a variable ${path} in red.xml and given a path value of 'Rel1'. Instead let's consider the value as "C:/Demo/Rel1/".

They have then called it in setting section as "**Resource**  ${path}/res_1.robot" of the testcase.robot file.
Now, Instead of that if I call it as "**Variable**  ${path}/var_1.py" in the setting section. 
And my var_1.py file will look something like this:
![image](https://user-images.githubusercontent.com/50138350/69590537-d741e900-1015-11ea-8927-f581b8b1d651.png)

And my TestCase will then look something like this:
![image](https://user-images.githubusercontent.com/50138350/69590676-3bfd4380-1016-11ea-85db-75c567f1e56b.png)

Now, are you saying, that during execution, I'll not be able to access any variables from the var_1.py file and my execution fails? And instead, I have to call it by providing --variable arguments to default launch configuration in Preferences?

**Comment by michalanglart** [comment]
I've recreated your example and it looks like this:

![vars](https://user-images.githubusercontent.com/14932410/69611713-b2a63b00-102e-11ea-9885-f12fb05fd22c.png)


The user guide chapter you have linked is specifically stating that:

> Variables provided in red.xml are used only by RED for validation purpose and are not added to Robot run command line.
During test execution variables have to be provided by Robot.

So - yes, I am saying that the variable mappings defined in red.xml are only used by RED in order to be able to recognize parameterized imports, because it cannot know the values of those variables so it cannot know what is imported without that.

>  And instead, I have to call it by providing --variable arguments

You can but this is only one of the options. This variable can be created by the logic of your suites/tests (for example using `Set Global Variable` keyword, using `--variable`, `--variablefile` or any other possible means of creating/injecting variables in running Robot execution).

The **Variable Mappings** was developed not because there was a need to provide a table of variables which would be then added to execution. It was developed because users were commonly using parameterized imports and RED was blind for them because it cannot statically guess the value which should be there in order to resolve this import.

**Comment by michalanglart** [comment]
I'm assuming it is now clear how it all works. Closing as there is nothing more to be done
