### ISSUE TITLE
keyword"Import Library" support

### ISSUE THREAD

**Issue by Ivan066** [nokia/RED#355]
RED version : latest
The imported library by using "Import Library" keyword under *** Keyword*** doesn't recongnized by RED.But the test goes successfully . In my project, "Import Library" keyword is normally used. Please give me some advice , thanks. 
![image](https://user-images.githubusercontent.com/29398125/70309376-5de19c00-1848-11ea-88cb-b6cedce04ae4.png)

**Comment by Ivan066** [comment]
![image](https://user-images.githubusercontent.com/29398125/70309646-ef510e00-1848-11ea-9af3-d82ac11619a7.png)

**Comment by michalanglart** [comment]
Hi,

RED does not support this and static analisys of code does not "see" the libraries imported dynamically. The case you have presented here could be theoretically more or less covered but in general this cannot be done just by analysing the source code.

It seems however that in your case you can simply import `OrionLibrary.login_case` and `OrionLibrary.navigation_case` in the Settings section. Why do you want to do it using keyword? Even it's documentation states that it should be used when really needed due to dynamic nature of the import:

> Imports a library with the given name and optional arguments.
>
> This functionality allows dynamic importing of libraries while tests are running. That may be necessary, if the library itself is dynamic and not yet available when test data is processed. **In a normal case, libraries should be imported using the Library setting in the Setting table**.

from: http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Import%20Library

**Comment by Ivan066** [comment]
OK.   My question can be solved by Using the Library setting , but the code is not pretty much, Thanks a lot.
