### ISSUE TITLE
Plugin for VSCode

### ISSUE THREAD

**Issue by venkatraju1284** [nokia/RED#356]
I find it as great plugin for Eclipse. As VSCode usage is growing in industry, would you please release a plugin?

**Comment by michalanglart** [comment]
As far as I know there is a plugin for VSCode already existing. We do not plan to extend VSCode however it may happen that we will re-use RED components in order to provide some implementation of Microsoft Server Language Protocol.If that would be the case then some kind of RED-based extension could be provided for VSCode too.

As for now: I'm closing this issue
