### ISSUE TITLE
Can add a custom Rflint rule only if contained in specific file name

### ISSUE THREAD

**Issue by apallier** [nokia/RED#366]
**RED version**: 0.9.3 on Debian Buster

**Steps to reproduce**
I add a custom Testcase rule:

```python
class CheckTestNamingConvention(TestRule):
    severity=WARNING
 
    def apply(self, testcase):
        """ ... """
```
I put this rule in a file named `namingConvention.py` and add it to the Rflint rules in Window -> Preferences -> Robot Framework -> Errors/Warnings -> RfLint validation

**Result**
RED is not able to take it into account:

1/ Cannot expand the rule file and see the rule in the "Rflint validation" configuration
2/ If I run Rflint, the rule is not applied

![image](https://user-images.githubusercontent.com/7916922/76604737-8ba54380-650f-11ea-9cbc-d2ac8639b528.png)

I must name the file `testcaseRules.py` if I want the rule to be accepted:
![image](https://user-images.githubusercontent.com/7916922/76604576-42ed8a80-650f-11ea-9572-9a4e7b85f575.png)
(Observe that the rule is "merged" with others from the built-in rule file: `PeriodInTestName`, `RequireTestDocumentation`...).

I don't know if it is a bug or a misunderstanding or a Rflint problem.

The RED doc screenshot seems to indicate that we can use any file name for rules:
Source: http://nokia.github.io/RED/help/user_guide/tools_integration/rflint.html
(Look at `custom_rule2.py` file)
![image](https://user-images.githubusercontent.com/7916922/76605166-4af9fa00-6510-11ea-922d-145437602a61.png)

**Comment by michalanglart** [comment]
Hi,

the file you've provided have errors: it uses `TestRule` and `WARNING` without importing those symbols.

This is visible if you would try to run `rflint` on your own:

```
> python -m rflint -R namingConvention.py suite.robot
rflint: namingConvention.py: exception while loading: name `TestRule` is not defined
```

You need to have:

```python
from rflint.common import TestRule, WARNING

class CheckTestNamingConvention(TestRule):
    severity=WARNING
 
    def apply(self, testcase):
        """ ... """
```

to make it work.

When it comes to renaming the file to `testcaseRules.py` - in this case you are creating a name-clash with built-in module and somehow it seems to work. This is related to the way rflint is loading the modules containg rules.

I'm afraid we cannot do anything about it. RED is asking `rflint` through some integration script to provide us with the rules. Unfortunately we are not able to catch this exception because it is handled inside `rflint` (by writing message to `stderr`), so we simply do not know if the file was loaded succesfully or not. Unfortunately `rflint` is written in a way which makes it hard to be integrated with other tools. In order to make it more or less work with RED we had to override some `rflint` internals (see https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts/rflint_integration.py) - there is no nice API which would allow us to do things we want to do.

**Comment by apallier** [comment]
Thank you for your answer. 
Sorry, I showed only a part of my code but the import actually exists and the rule actually works (I retest with a command line to be completely sure).

The simple fact of renaming the file `testcaseRules.py` is sufficient to make it work, without any code change...

**Comment by michalanglart** [comment]
Ok, then this sample does not reproduce your problem. Can you share the actual code?

**Comment by apallier** [comment]
Whole file:
```python
from rflint.common import TestRule, WARNING

class CheckTestNamingConvention(TestRule):
    """ Check testcase naming convention """
    severity = WARNING
    
    def apply(self,testcase):
        testcase_name_title = testcase.name.title()
        if testcase.name == testcase_name_title:
            return
        self.report(testcase, f'Naming convention error: should be "{testcase_name_title}"', testcase.linenumber)
```

**Comment by michalanglart** [comment]
I've checked it and this rule works fine for me. I can see it normally at preference page and it is properly applied when running analisys.

The only problem I run into was that rflint 0.9 as well as 1.0 is not yet ready for RF 3.2 and it does not work at all with 3.2 beta2.

What are the versions of your python/robot/rflint?

**Comment by apallier** [comment]
Hi, my versions are:
Python: 3.7.3
robotframework: 3.1.2
robotframework-lint: 1.0

You are right, it's a problem of versions. I just downgrade Rflint to **0.9** and it works as expected:

![image](https://user-images.githubusercontent.com/7916922/77046985-3d3aed80-69c4-11ea-80c3-1d3f362c08d5.png)

Thank you for your help.

**Comment by michalanglart** [comment]
Hmm, but it was working for me in both rflint 1.0 and 0.9 under python 3.7.1 and RF 3.1.2...

Both versions were not working when using RF 3.2 beta2

**Comment by apallier** [comment]
I don't understand anymore too. Since your last message I wanted to check: I upgraded Rflint to 1.0 and now It works! as you indicate...
As you can see in my first screenshot, I'm sure it didn't work...
Maybe a PYTHONPATH problem because when I launch RED this morning, Eclipse indicates that PYTHONPATH has been changed and I validated the suggested PYTHONPATH.
Anyway, it works now. Thank you.

**Comment by michalanglart** [comment]
It's possible that restarting RED could help here. Glad to hear it works anyway!
