### ISSUE TITLE
Add posibility to provide arguments for library imports in red.xml

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#47]
It shall be possible to provide arguments when importing library in red.xml. Otherwise libraries which needs arguments are marked as non-accessible.

**Comment by docian** [comment]
no... it has no effect. I'm adding the library like this:
*** Settings ***
Library   PaymentMessageUtils  arg0  arg1  arg2 ... arg10

**Comment by michalanglart** [comment]
We've had technical obstacle which was preventing implementation of this issue but the good news is that we're about to remove this obstacle with next version.

**Comment by binithb** [comment]
IMHO it'a a basic feature and will be nice to have priority

**Comment by michalanglart** [comment]
We'll put that info in user guide for now. I will move the task closer to the top of backlog.

**Comment by humbienri** [comment]
Isn't this more of a linter issue?  Intellisense or lack thereof?  The code still runs right?

**Comment by michalanglart** [comment]
> The code still runs right?

Which code runs right? What exactly are you asking of? 

RED is not able to generate library specification file for a library which requires arguments in its constructor. Without specification file it will report errors about unknown keywords; it will not show library keywords in content assistant; you will not be able to Ctrl+click on keyword to get to the source; you will not see the documentation of library and its keywords.

**Comment by michalanglart** [comment]
This issue is getting closer to the top of the backlog so hopefully we will fix it eventually

**Comment by humbienri** [comment]
@michalanglart when I wrote my last comment I was seeing the "buggy/ugly" behavior as described but I was still able to execute and run my robot tests.  That is what I meant by, "okay, sure...lines and KeyWords are being flagged as red but you can still run your test code".

So all the "convenient" things you can do like CTRL+Click and documentation that is useful during the development of the tests will not work.  But when it comes to run time and executing the tests, they will work just fine.

**Comment by michalanglart** [comment]
> But when it comes to run time and executing the tests, they will work just fine.

Yes of course - RED is not executing tests it just asks `robot` to do it so execution would work fine.

> As for generating the library spec file, do you mean the libdoc documentation file? Isn't the workaround to just generate that file manually from the command line?

Yes, sure. You can generate the file manually (it has to be the xml file) using `robot.libdoc` module and add it to red.xml. After all this is exactly what RED is doing in the background with recognized libraries however it still does not support providing arguments when generating those files.

**Comment by Mario-P** [comment]
> 
> 
> @michalanglart when I wrote my last comment I was seeing the "buggy/ugly" behavior as described but I was still able to execute and run my robot tests. That is what I meant by, "okay, sure...lines and KeyWords are being flagged as red but you can still run your test code".
> 
> So all the "convenient" things you can do like CTRL+Click and documentation that is useful during the development of the tests will not work. But when it comes to run time and executing the tests, they will work just fine.
> 
> As for generating the library spec file, do you mean the libdoc documentation file? Isn't the workaround to just generate that file manually from the command line?

You don't even need RED to run robot tests. RED is an IDE and things like Ctrl+C, libspec creation, documentation are the crucial part of any IDE.

**Comment by humbienri** [comment]
I thought I had a clear understanding of this, but based on my struggles in the last 2 days, clearly I don't.

I thought one could get around the problem of RED not being able to cope with arguments to custom python libraries by just doing so manually via the DOS commandline and a libdoc call to generate the XML spec file.

After that, one would be able to debug/step through the python code.  Wrong?

**Comment by michalanglart** [comment]
About debugging python code: you are aware that RED itself is not able to debug python code and it needs for example PyDev in order to able to do that? This is described here: http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html

As to the question: no, not wrong. I've just checked and it works (together with PyDev of course). The only thing I needed to do is to additionally extend PYTHONPATH with the path to the library (additional entry in red.xml file). Here is my example project you can check - after putting breakpoints in both robot code and argsLib.py code I was able to debug both of them:

[example.zip](https://github.com/nokia/RED/files/3256756/example.zip)

**Comment by humbienri** [comment]
Yes, I am aware that to debug python I need and have PyDev.  And in a previous effort I was able to debug both robot files and python files with the coordination/cooperation of both RED (for robot debugging) and PyDev (for python debugging).

I launch the Pydev Start Debug Server and then I launch my robot Debug configuration and it worked.

I'm just not having the same level of luck once I incorporated this locustio stuff with a constructor (which might not be needed, maybe).

The idea is that this custom python library for making api calls will be used by both the UI robot tests as well as the locust load/performance tests.  That is my goal and why I having to inherit from the TaskSet class of locust.

The part about having to extend the PYTHONPATH caught my eye.  In the screen shot below, is it necessary to have both?  Notice I had to use the XML file for the lib documentation.

![_2019Jun05102424](https://user-images.githubusercontent.com/1178569/58968881-63b4d280-877c-11e9-9d4f-da5687d771f9.png)

**Comment by michalanglart** [comment]
> The part about having to extend the PYTHONPATH caught my eye. In the screen shot below, is it necessary to have both? Notice I had to use the XML file for the lib documentation.

Yes. This is visible in my `example` project. The thing is:
- in order to perform by-name import of a library Robot needs to know where this library is. To do this the path to the library needs to be in your PYTHONPATH or it needs to be passed with `-P` argument switch when executing tests through Robot
- when you're adding some library to `red.xml` by-source (pointing to some `file.py`) then RED will automatically add parent path of this library into `-P` switch once you start your tests from RED
- if you're adding only specification file then this library is kind-of-virtual; in general there may be no source of such library at all (of course execution would not work in such case) so as a result parent path of such virtual library is not added via `-P` switch - it must be added differently for example in this field on the right.

**Comment by michalanglart** [comment]
Implemented in 0.9.0. See http://nokia.github.io/RED/help/user_guide/project_config/libraries.html user guide topic for more information on that
