### ISSUE TITLE
Error in RED while starting debugging in Eclipse [html support in debug]

### ISSUE THREAD

**Issue by BeastModeActivated** [nokia/RED#52]
Eclipse IDE for C/C++ Developers
Version: Neon.1a Release (4.6.1)

RED version: 0.7.1.201610040910

We are using Eclipse with RED for writing robot test in *.txt format and use python libraries.
These work fine when I run the test case.
But on starting in debug mode, I always get the following error and it stops debugging: 

"An internal error occurred during: "Robot Event Dispatcher".
Index: 0, Size: 0"

I checked in workspace directory .log file. I have attached that error in error.txt file.

[error.txt](https://github.com/nokia/RED/files/539147/error.txt)

Please help in fixing this. Let me know in case you need further information.

**Comment by adam-wypych** [comment]
Can You provide Your test suite `*.txt` file? It can have even obfuscated values, but we need to check what happen.

**Comment by BeastModeActivated** [comment]
Following is sample test that i executed:
It works fine when running. Gives error when started in DEBUG mode.
*** Settings ***

*** Variables ***
${serial_id}    ${EMPTY}

*** Keywords ***
Capture fields entered in Transaction View While Creating New Transaction
    [Arguments]    ${trans_fields_1}    ${trans_fields_2}    ${sep_1}    ${output_1}
    ${serial_id}    Set Variable    ${EMPTY}

**Comment by adam-wypych** [comment]
@BeastModeActivated the file which You provide is resource file on which Run/Debug shouldn't be even enable, so maybe can You show also Test Suite file? Thanks in advance.

**Comment by BeastModeActivated** [comment]
Suite Executor: Robot Framework 2.9rc1 (Python 2.7.8 on win32)

**Comment by adam-wypych** [comment]
I think about file, where 
```robotframework 
*** Test Case ***
``` 
section exists, it should be in command line:
Command: 

```
C:\Python27\python.exe -m robot.run -P D:\userdata\wypych\Downloads\remoteswinglibrary-2.2.0.jar --listener C:\Users\wypych\AppData\Local\Temp\RobotTempDir3677471094168952189\TestRunnerAgent.py:51821:False -s REDSimple.Test -t REDSimple.Test.T1 D:\userdata\wypych\runtime-New_configuration\REDSimple
```

The suite file in may case is REDSimple/Test.robot (its described by parameter `-s`)

**Comment by adam-wypych** [comment]
Ok, uff thanks a lot last Your comment helps - 

> Test suite file is attached (please rename it to test.html)

We do not support `html`. See release note 0.7.1:
https://github.com/nokia/RED/releases/tag/0.7.1 bullet: _File support: .robot, .txt, .tsv_
 As debug start we trying to read content of file and therefore parser return to debugger empty list of parsed files. Please try to convert file it to txt, tsv or robot. 

Additionally `html` is deprecated by RF.

**Comment by BeastModeActivated** [comment]
We have HTML file where we write test scenarios. and actual keywords are written in .txt file.
Is there a workaround from where I can debug keywords without changing all my html test scenario files ?

**Comment by adam-wypych** [comment]
For now the only workaround is to use `tidy` (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id783) tool and convert Your `html` scenarios to corresponding `.robot`. Or to create some debug scenario in supported format with keyword executed in place.

Anyway we will check if will be possible without directly support `html` to process keywords from supported file formats.

**Comment by BeastModeActivated** [comment]
Thanks @adam-wypych

**Comment by BeastModeActivated** [comment]
@adam-wypych Is there any plan to support this in near time ? 

"Anyway we will check if will be possible without directly support html to process keywords from supported file formats."

**Comment by adam-wypych** [comment]
Ok, I will route question to correct person for project decission :)

@KrzysztofJozefowicz Can You answer @BeastModeActivated question?

**Comment by KrzysztofJozefowicz** [comment]
Hi
HTML format flawed by design as mentioned in robot framework guide ( " The main problem with HTML format is that editing these files using normal text editors is not that easy. Another problem is that HTML does not work as well with version control systems because the diffs resulting from changes contain HTML syntax in addition to changes to the actual test data." ) although it has some advantage for testcase presentation as documentation for non-tech savvy folks. 

We do not want to invest too much with html support as there are already solutions for testcase conversion from html to .robot and with limited man power we would like to focus on core functionalities. 

From html support, RED could know the KW/vars from html resources to get rid of error markers in testsuites which uses html resources. 

For your case, you can temporary convert your main test suite from html to .robot/csv with built-in Tidy ( https://robot-framework.readthedocs.io/en/3.0/_modules/robot/tidy.html ) and run such converted top level suite in Debug to have KW from resources ready for debugged.  Alternatively we could implement to temporary run tidy for html files to convert them to .robot before running testes or debug.  As there is already workaround this is low priority case for us, I cannot give you any estimates for that.

**Comment by BeastModeActivated** [comment]
@adam-wypych You mentioned 
"Additionally html is deprecated by RF."

Do you have any link where RF mentions that html is no longer supported ?

**Comment by adam-wypych** [comment]
@BeastModeActivated here You have the topic related to it: https://groups.google.com/forum/#!topic/robotframework-users/TygdvA-Ba2Y 

and one bug related to performance issue with html:

https://github.com/robotframework/robotframework/issues/2365

**Comment by BeastModeActivated** [comment]
@adam-wypych I see it is still under discussion. or has it already been decided ?
There was no conclusion in the google group post.

**Comment by adam-wypych** [comment]
@BeastModeActivated we are different team and we do not develop Robot Framework. Therefore what I see is that is some plan to skip support for HTML (even this RF github issue #2365) and since its complicated format we also do not see any benefitials for support it.
