### ISSUE TITLE
Open declaration doesnt work properly when navigating from Robot file to Python File

### ISSUE THREAD

**Issue by BeastModeActivated** [nokia/RED#54]
Eclipse IDE for C/C++ Developers
Version: Neon.1a Release (4.6.1)
RED version: 0.7.1.201610040910
Suite Executor: Robot Framework 2.9rc1 (Python 2.7.8 on win32)

We have written keywords in *.txt file where we are importing Python libraries.
If in *.txt file(keyword file) i select a function that is written in python and do "Open declaration" then it just opens the Python file and cursor is at top of file, it should be at the point where that function is declared.
Please check this.

**Comment by adam-wypych** [comment]
@BeastModeActivated Unfortunatelly we do not support jump to line, where keyword is defined. Our source code analysis base on what `libdoc` provides for us. I made some GitHub issue in RF project, but unfortunatelly I didn't have time to solve it: https://github.com/robotframework/robotframework/issues/2350 .

We have some internal backlog issue for that.

**Comment by BeastModeActivated** [comment]
Thanks Adam-wypych

**Comment by BeastModeActivated** [comment]
@adam-wypych Jump to line is supported in https://github.com/millennialmedia/pyro/wiki
Can we have this feature in RED as well ?

**Comment by adam-wypych** [comment]
@BeastModeActivated regarding usage of Pyro I didn't try it, but I found that is mostly PyDev (**so only Python**) connected, I can only imagine that is just heuristic search, without support for robot decorators. Therefore base on this knowledge I think about RF support for say what is keyword and what is it name.

**Comment by adam-wypych** [comment]
I got response from @pekkaklarck that finally he rejected possibility to extends Libdoc to correctly provide line numbers from source code, with statement: _"As I commented above, it's not a feature normal Libdoc users would need, implementation is complex, and it isn't possible to implement this in generic manner with all supported library types."_

So I think the best way to solve this problem is to fork and modify libdoc tool (change it name also) from robotframework as I already made in pull request https://github.com/robotframework/robotframework/pull/2514 and delivery together with RED as separate ZIP file, add to Python path during runtime (https://blogs.gnome.org/jamesh/2012/05/21/python-zip-files/). I see that Libdoc is not changing so often.

**Comment by michalanglart** [comment]
@adam-wypych - we will release 0.7.5 in next days, where @modrz have implemented and extended your proof-of-concept which uses dry run to locate keywords. Apart from java libraries we are recognizing keywords in python libraries pretty well, so we'll stick to that implementation as for now.

**Comment by adam-wypych** [comment]
@michalanglart ok no problem so as part of this bytecode compiled Java code should work also (see https://github.com/robotframework/robotframework/pull/2514/files#diff-d0d40e8ea0b9a10b678ffcac2632a885 ). The only problem will be Java source code files.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.5
