### ISSUE TITLE
Add Environment variables support

### ISSUE THREAD

**Issue by mfaulkner9294** [nokia/RED#67]
Add a tab to the Run/Debug settings to allow for the setting/override of environment variables.

**Comment by michalanglart** [comment]
As far as I understand this should be general purpose tab where you can define any environment variables which will be passed to interpreter, right?

![env](https://cloud.githubusercontent.com/assets/14932410/21612610/3d184bf0-d1d2-11e6-831f-6c2e5f1c7404.png)

If the tab from image above is enough then it can be very easily added, since this is general purpose tab which already exist in eclipse and is added to many different run configurations.

**Comment by mfaulkner9294** [comment]
Yes, that is the tab, but I think there may need to be something that sets those variables in the environment where robot is invoked...

**Comment by michalanglart** [comment]
Yes, of course - one thing is to add the tab and another thing is to append/override variables when starting robot, but anyway it should be easy :)

**Comment by mfaulkner9294** [comment]
Sounds great!

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.5

**Comment by mfaulkner9294** [comment]
Seems to work fine for me.  Thanks.
