### ISSUE TITLE
Add support for Suite Variables

### ISSUE THREAD

**Issue by MarcinAtgithub** [nokia/RED#68]
Hi
In my project at Nokia I have a resource file that runs:
Set Suite Variable ${VAR}

Later in the suite test case I use that variable.
RED version 0.7.3.2016.12080954 shows an error:
Variable 'VAR' is used, but not defined

**Comment by michalanglart** [comment]
Hi,

this is in essence same issue as #7 and also a bit similar to #28

We are aware of this problem but so far we were reluctant to implement this mainly because of two problems which such constructions:

First thing is that in line:
`Set Suite Variable  ${VAR}` 
the VAR variable is created dynamically, while RED is performing static code analysis - in general in some test runs it may be created, while in other it won't  (see global variable example described by @adam-wypych in #7)

Secondly: RED is generating library specification using robot.libdoc. The specification gives us information like how many keywords are there, what are their names, how many arguments they require or what's their documentation text. From those limited specifications we're not able to distinguish between ordinary keywords for which we should should show an error when such keyword is using the variable we're not seeing from those magical keywords like Set Suite Variable for which the error should not be shown. 

Basically this means that the only way to support it is to manually prepare a list of magical keywords and use it with validation. The problem is wider and touches not only variables, but keywords too - as in #28 where we would need to have another list of differently-magical keywords which threat some of arguments as a names of other keywords.

The possibilities from my point of view are:
- in this particular case: define the variable statically as described in #7 within Variables section
- we are planning to implement suppressing particular errors/warnings for given line/file/test case/keyword/etc (it's to be implemented rather soon), so it would be possible to remove this error, but on the other hand it cannot be used in #28
- in theory library specifications generated by robot could be somehow augmented but this would also require extension of RF API so that the magical keywords can be declared in a way which can be then analyzed by libdoc in order to generate proper information. I think this is not likely to happen
- manually implement list of magical keywords - maybe there would be only couple of such and we could also limit it to standard libraries...


We need to discuss it within the team.

**Comment by KrzysztofJozefowicz** [comment]
@MarcinAtgithub , can you contact us via internal mail in Nokia for further updates and questions if needed?

**Comment by michalanglart** [comment]
Similarly as in #7 - we do not want to push the analisys further and look deeper if there may be some `Set Global/Suite/Test Variable` keyword called.
