### ISSUE TITLE
How to write to 'Message Log' view

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#69]
While developing a Python listener for RBF I'd like to write to the Message Log, not the console, a line that the listener has started. 

While trying virtually all methods of the logger class in python I've not figured out how to write to the message log.

**Comment by michalanglart** [comment]
Hi,

it works as follows: when RED is starting test it attaches our listener (https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/resources/org/rf/ide/core/executor/TestRunnerAgent.py - this one to be precise, it is taken from RIDE code with some changes for bug fixing and debug handling). Next this listener is responsible for communicating between python process running tests and RED. In Message Log view RED is printing everything which was sent to it from log_message() method of listener plus some lines about test start/end. 

The crucial thing here is that as you can read in RF user guide (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listeners-logging) the listeners are not notified about messages logged from inside of listener (see note in 4.3.4 paragraph) which means that our listener is not notified that your listener have logged something, so as a result nothing is send to RED in order to be printed inside Message Log view.

We need to take a look at it deeper in order to check if there is anything we can do on our side.

**Comment by kootstra** [comment]
Thanks for the clear explanation. So in the end the source is the listener and not the regular functionality. For now this closes this question for me. Thanks for taking the time.
