### ISSUE TITLE
red.xml and relative paths

### ISSUE THREAD

**Issue by mkswdev** [nokia/RED#73]
It would be great to be able to define robotExecEnvironment and referencedLibrary in red.xml as relative paths. Currently it is not possible to easily share red.xml across team.

**Comment by michalanglart** [comment]
Hi, 

as to the relative paths for libraries: I think we have this issue raised somewhere, although I haven't seen it recently somewhere near the top of our backlog. We'll discuss it soon.

As to the python environment: it is probably achievable, but I think I'm missing something because I don't see the use case in which this would be an improvement. Instead of requiring team members to install python under some constant location there will be a requirement like "you need to put your project two directories above your python and then into directory A/B/project". Moreover you don't need to provide this location in red.xml and use one as defined in preferences, so every team member can put python wherever he or she wants to, you just need to tell them which version they should use.

Would you be able to describe some use case in which relative path to environment would be desired?

**Comment by mkswdev** [comment]
Hi, our requirement is to run Robot tests in controlled environment to avoid problems caused by different version of Iron Python or Robot Framework, so we have C# project and Iron Python with Robot Framework robot tests in version control system so every developer does not need to install the right version of Iron Python and Robot Framework. So every developer  has the same folder structure for the project (including IronPython, Robot, robot tests etc) and we also have BAT files to run all tests and to start RIDE in specified directory. Only difference is, that every developer has slightly different root folder with sources or different hard drive. We would like to use RED, but without relative paths it is just harder, not impossible.

**Comment by michalanglart** [comment]
Ok, this makes sense for me - somehow I wasn't thinking of python interpreter as part of project, but well - why not.

We'll talk this through next monday within the team. It requires a little bit of work, so don't expect it be implemented with 0.7.5, as we are about to release it very soon. On the other hand it seems that 0.7.5 will be able to recognize and work with 64-bit IronPyton as requested in #71 :)

**Comment by mkswdev** [comment]
Thanks for your answer. As I wrote, we can already use RED with some manual steps written in user guide, but it usually ends with some user errors. We really appreciate your work on RED.

**Comment by modrz** [comment]
Fixed in 0.8.6
