### ISSUE TITLE
Does RED supports remote debug of Robot test cases run remotely inside Docker Containers?

### ISSUE THREAD

**Issue by PWojtal** [nokia/RED#80]
Does RED supports remote debug of Robot test cases run remotely inside Docker Containers?

**Comment by KrzysztofJozefowicz** [comment]
We do not have much experience with Docker although I do not see any reasons why this should not be already possible. From RED&Robot point of view, container should have installed python interpreter (or other python-like compatible with robot) with robot and SUT, for remote debug RED needs direct network connection to connect with robot inside container. 
Fell free to contact us with specific questions, this is interesting case.

**Comment by michalanglart** [comment]
Hi,

RED supports remote debug in general and it works like this:
- inside RED you create a new Run Configuration in which you specify IP & port
- special listener file (TestRunnerAgent.py) is exported from RED
- debug session is started on RED side
- on remote machine tests are executed with exported listener attached

In case of docker its just a matter of configuring networking, so that tests running in container and RED can communicate. In order to check if it works I did quick check as follows:

- created 'project' in RED with suite.robot containing some case, added breakpoint there
- created a run configuration with IP set to 127.0.0.1 and port=12345
- exported TestRunnerAgent.py directly to 'project' directory
- then run the container:
`sudo docker run -i -t --name robot ubuntu:latest`

- inside the container python has to be installed:
`apt-get update`
`apt-get upgrade`
`apt-get install python-pip`
`python -m pip install robotframework`
`exit`

- again on host machine, copied the project and started container with exposed port:
`sudo docker cp /path/to/project robot:/project`
`sudo docker commit robot robot_image`
`sudo docker run --net="host" -p 12345 -i -t robot_image`

- then run the debug in RED, it will wait for tests to start
- inside the container start the tests with agent attached:
`python -m robot.run --listener /project/TestRunnerAgent.py -s project /project`

After that debug properly suspended at the breakpoint I've defined and it worked the way I expected.

**Comment by KrzysztofJozefowicz** [comment]
This scenario will be possible to execute when #70 will be provided. Investigation already started.

**Comment by KrzysztofJozefowicz** [comment]
as #70 is provided, script configuration allow user to create script to execute tests on remote env.
