### ISSUE TITLE
Maven Jython Run Script not working.

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#90]
Following the step-by-step description for [integrating Maven Plugin into RED](https://github.com/nokia/RED/blob/9d62dccce18ee7f3051162d05bf3d027e33dccef/red_help/user_guide/maven.html.md) I was able to get the standard libraries recognized. However, when I run a simple test case the below error message. The message complains about the **-J-cp .** console argument. This particular argument is not supported by the Launch4J wrapper. When removed the command works as expected and connects with RED.  However, as a manual workaround this won't work for debugging as the debugger is already closed before one can start it manually. 
```
Command: C:\Eclipse\Jython38\jython.exe -J-cp . 
-m robot.run 
--listener C:\Users\User\AppData\...\TestRunnerAgent.py:55095:False 
-s HelloWorldMaven.HelloWorld C:\Eclipse\Workspace\HelloWorldMaven
Suite Executor: Robot Framework 3.0.2 (Jython 2.7.0 on java1.8.0_71)
Unknown option: J-cp
usage: jython [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `jython -h' for more information.
```

**Comment by michalanglart** [comment]
Hi,

We are currently working on #70 in order to provide generic method of running tests using custom batch/bash/etc scripts and it should also make it easier to integrate maven with RED and RF. 

I think this issue will be resolved with new feature as well as other issues like running tests using Gradle, pabot etc

It will be for sure available in next release however I cannot give its ETA precisely as of today, but I wouldn't expect it sooner than 2 weeks from now.

**Comment by kootstra** [comment]
That is indeed what I thought as well. Just wanted to provide an additional reason to implement the flexible run/debug feature.

**Comment by michalanglart** [comment]
I'm leaving this issue open and it should be closed after release is done and article on maven integration is changed accordingly

**Comment by KrzysztofJozefowicz** [comment]
This is already covered by running with custom scripts: http://nokia.github.io/RED/help/user_guide/launching/local_launch_scripting.html
