### ISSUE TITLE
Filter libraries Keywords in Content Assist feature

### ISSUE THREAD

**Issue by MarcoAPA** [nokia/RED#92]
Im working on a custom library of Keywords and I would like to know if there is a way to hide all suggested **Keywords** from the Standard libraries and show only my custom library Keywords. 
Is it possible to do this also with **Variables** and filter Content Assist Variables shown?

**Comment by michalanglart** [comment]
Hi,

no currently there is no such possibility, however it shouldn't be hard to provide such configuration in preferences.

In case of variables would you like to have Global/Built-in variables filtered out?

**Comment by MarcoAPA** [comment]
Yes, I want Built-in variables filtered out, is it possible to do that?

About the Standard libraries filter, instead of provide the configuration via preferences, can I create a Robot project without this Standard library by default and only use my custom library?

Thank you for the answer @michalanglart

**Comment by michalanglart** [comment]
No, its not possible too to filter out built-in variables as for now. There is user-defined filtering in content assistant implemented. Every keyword coming from library or resource imported by your file is visible in content assist. Same for variables.

You cannot create project without standard libraries. Project is always using some Python+Robot environment and RED is asking it what are the standard libraries. In the end you can probably delete the library and/or modify Robot code so that it will no longer see for example Collections library, but I don't know what can be broken in RF this way.

I think it would be better to have some content assistant filtering set up in Red preferences.

**Comment by MarcoAPA** [comment]
Thanks for the quick response. I have another question that its not related to this one, so I have opened another issue. You can label these issues as questions. Thanks again @michalanglart
