### ISSUE TITLE
How to get automatic update notification?

### ISSUE THREAD

**Issue by nikhilrajgarhia** [nokia/RED#94]
[https://groups.google.com/forum/#!topic/robotframework-users/522lmXEwCA4](url)

**Comment by KrzysztofJozefowicz** [comment]
Please describe your issue. From link I do not see any connections with RED.

**Comment by nikhilrajgarhia** [comment]
Whenever there are any updates for Robot framework, we do not get any auto notifications. Just wanted to know is there any way to get it automatically, if not, can we have this feature (I am using Eclipse and the RED plugin for Robot Framework).

**Comment by michalanglart** [comment]
No, currently there is no way you can do it from RED. 

The only way probably is to write some script and schedule it for execution from time to time, but this has to be done outside RED/eclipse. 

We'll discuss this issue and let you know if we want to have it incorporated into RED.

**Comment by nikhilrajgarhia** [comment]
Yes, sure, it would be great having this incorporated with RED.

**Comment by KrzysztofJozefowicz** [comment]
Hi
RF does not change to frequently (apart from last 3 months with RF 3.0 releases), either you can update it automatically by using pip with cron/scheduller ( **pip install -U robotframework** ) or it way be wise to watch RobotFramework repository on GitHub to get notifications - https://github.com/robotframework/robotframework 
One advantage is in case of RF ReleaseCandidate announcement, you can check changes and verify if those are not breaking anything in your test material before full release is provided. This will not be possible with any embedded option in RED.
Moreover, if you create tests on multiple machines (team work or CI env) you have to be sure that everybody uses the same version of RF to reduce possible errors due to version mismatch. 

I would propose to use **pip install -U robotframework**  instead of relaying on anything else.
