### ISSUE TITLE
Issue with executing tests.

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#97]
When try to launch tests after upgrading to version 0.7.6 the following error is displayed:
An internal error occurred during: "test.name".
org.eclipse.debug.core.model.RuntimeProcess cannot be cast to org.robotframework.ide.eclipse.main.plugin.launch.IRobotProcess

**Comment by macasio14** [comment]
For those of up new to RED, can you clarify what files contain the configurations we need to replace?

**Comment by michalanglart** [comment]
Launch configuration is a generic term in eclipse. This is a description of how something should be launched, what parameters should be used and so on. Whenever you launch something from eclipse it probably creates some kind of launch configuration and use it. Technically launch configuration is a XML file which eclipse stored somewhere deep inside its metadata directory.

RED is no exception here - whenever you're running your Robot suites it will re-use some launch configuration (if there is some matching configuration already defined), or it will create new one and use it.

You can view, edit, export or remove your launch configurations by opening Run menu and then choosing either Run Configurations or Debug Configuration menu item. On left side inside this dialog you will see 'Robot' category and all your existing launch configurations which RED created. You can edit them there and you can also remove them (right mouse button on configuration -> Delete).

In order to avoid the exception from this issue you have to remove all the existing configurations which were created with RED 0.7.5 or earlier, because RED 0.7.6 is not able to launch tests using those old ones.

For more on launching tests see chapter in RED user guide: http://nokia.github.io/RED/help/user_guide/launching.html (there are also subchapters, this guide can also be displayed inside RED by Help -> Help Contents menu).

Hope this helps and clarifies the topic!

**Comment by Mario-P** [comment]
I've removed all and created started from scratch. It worked only then.

2017-04-12 17:18 GMT+02:00 macasio14 <notifications@github.com>:
